package main

import (
	"encoding/json"
	"fmt"
	"math"
	"strconv"
	"strings"
)

func (g *webGenerator) contractTestTS() string {
	var builder strings.Builder
	builder.WriteString("// Generated by BlackLang. Do not edit manually.\n\n")
	builder.WriteString("import assert from \"node:assert/strict\";\n")
	builder.WriteString("import fs from \"node:fs\";\n")
	builder.WriteString("import path from \"node:path\";\n")
	for _, entity := range g.entitiesWithGeneratedValidation() {
		builder.WriteString(fmt.Sprintf("import { %s } from \"./validation/%s\";\n", g.validationImportNames(entity), strings.ToLower(entity.Name)))
	}
	builder.WriteString("\n")
	builder.WriteString("type ValidationResult = { valid: boolean; value?: Record<string, unknown>; errors?: string[] };\n")
	builder.WriteString("type OpenAPIShape = { openapi?: string; paths?: Record<string, Record<string, any>>; components?: { schemas?: Record<string, unknown> } };\n\n")
	builder.WriteString("const spec = JSON.parse(fs.readFileSync(path.join(process.cwd(), \"openapi.json\"), \"utf8\")) as OpenAPIShape;\n")
	builder.WriteString("const paths = spec.paths ?? {};\n")
	builder.WriteString("const schemas = spec.components?.schemas ?? {};\n\n")
	builder.WriteString("const packageJson = JSON.parse(fs.readFileSync(path.join(process.cwd(), \"package.json\"), \"utf8\")) as { scripts?: Record<string, string> };\n")
	builder.WriteString("const packageScripts = packageJson.scripts ?? {};\n\n")
	builder.WriteString("const secretManifest = JSON.parse(fs.readFileSync(path.join(process.cwd(), \"security\", \"secrets.json\"), \"utf8\")) as { policy?: string; providerFile?: string; references?: Array<{ name?: string; sources?: string[]; sensitive?: boolean; required?: boolean }> };\n")
	builder.WriteString("const secretReferences = secretManifest.references ?? [];\n\n")
	if len(g.program.Migrations) > 0 {
		builder.WriteString("const migrationManifest = JSON.parse(fs.readFileSync(path.join(process.cwd(), \"migrations\", \"manifest.json\"), \"utf8\")) as { runner?: { planCommand?: string; applyCommand?: string; policy?: string }; migrations?: Array<{ name?: string; file?: string; operations?: unknown[] }> };\n")
		builder.WriteString("const migrationItems = migrationManifest.migrations ?? [];\n\n")
	}
	if g.hasBrowserChecks() && !g.isAPIOnlyTarget() {
		builder.WriteString("const browserMatrixManifest = JSON.parse(fs.readFileSync(path.join(process.cwd(), \"tests\", \"browser-matrix.json\"), \"utf8\")) as { planCommand?: string; runCommand?: string; policy?: string; targets?: Array<{ name?: string; family?: string }> };\n")
		builder.WriteString("const browserMatrixTargets = browserMatrixManifest.targets ?? [];\n\n")
	}
	if g.hasServices() {
		builder.WriteString("const serviceManifest = JSON.parse(fs.readFileSync(path.join(process.cwd(), \"services\", \"manifest.json\"), \"utf8\")) as { services?: Array<{ name?: string; apis?: Array<{ name?: string; path?: string; method?: string }> }> };\n")
		builder.WriteString("const serviceItems = serviceManifest.services ?? [];\n\n")
	}
	if g.hasOpsObserve() {
		builder.WriteString("const observabilityManifest = JSON.parse(fs.readFileSync(path.join(process.cwd(), \"ops\", \"observability.json\"), \"utf8\")) as { provider?: string; endpointEnv?: string; protocol?: string; mode?: string; signal?: string; traceContext?: string; delivery?: string; exporter?: { nonBlocking?: boolean } };\n\n")
	}
	builder.WriteString("function assertPath(route: string, method: string) {\n")
	builder.WriteString("  assert.ok(paths[route]?.[method], `${method.toUpperCase()} ${route} should exist in openapi.json`);\n")
	builder.WriteString("}\n\n")
	builder.WriteString("function assertSchema(name: string) {\n")
	builder.WriteString("  assert.ok(schemas[name], `${name} schema should exist in openapi.json`);\n")
	builder.WriteString("}\n\n")
	builder.WriteString("function assertValid(result: ValidationResult, label: string) {\n")
	builder.WriteString("  assert.equal(result.valid, true, `${label} should be valid: ${JSON.stringify(result.errors ?? [])}`);\n")
	builder.WriteString("}\n\n")
	builder.WriteString("function assertInvalid(result: ValidationResult, label: string) {\n")
	builder.WriteString("  assert.equal(result.valid, false, `${label} should be invalid`);\n")
	builder.WriteString("  assert.ok(Array.isArray(result.errors), `${label} should include errors`);\n")
	builder.WriteString("}\n\n")
	builder.WriteString("assert.equal(spec.openapi, \"3.1.0\");\n")
	builder.WriteString("assert.ok(secretManifest.policy?.includes(\"secret values must stay out of .black source\"));\n")
	builder.WriteString("assert.equal(secretManifest.providerFile, \"scripts/secrets-provider.mjs\");\n")
	builder.WriteString("assert.equal(packageScripts[\"security:secrets:preflight\"], \"node scripts/secrets-provider.mjs --preflight\");\n")
	builder.WriteString("assert.ok(fs.existsSync(path.join(process.cwd(), \"scripts\", \"secrets-provider.mjs\")), \"secret provider preflight script should be generated\");\n")
	builder.WriteString(fmt.Sprintf("assert.ok(secretReferences.some((ref) => ref.name === %q && ref.sensitive === true), \"database env reference should be tracked without printing its value\");\n", g.databaseEnvName()))
	if len(g.program.Migrations) > 0 {
		builder.WriteString("assert.equal(packageScripts[\"db:migrate:plan\"], \"tsx src/migrate.ts --plan\");\n")
		builder.WriteString("assert.equal(packageScripts[\"db:migrate\"], \"tsx src/migrate.ts --apply\");\n")
		builder.WriteString("assert.equal(migrationManifest.runner?.planCommand, \"npm run db:migrate:plan\");\n")
		builder.WriteString("assert.equal(migrationManifest.runner?.applyCommand, \"npm run db:migrate\");\n")
		builder.WriteString("assert.ok(migrationManifest.runner?.policy?.includes(\"plan mode is read-only\"));\n")
		builder.WriteString(fmt.Sprintf("assert.equal(migrationItems.length, %d);\n", len(g.program.Migrations)))
		builder.WriteString("assert.ok(fs.existsSync(path.join(process.cwd(), \"src\", \"migrate.ts\")), \"migration runner should be generated\");\n")
	}
	if g.hasBrowserChecks() && !g.isAPIOnlyTarget() {
		builder.WriteString("assert.equal(packageScripts[\"test:e2e:plan\"], \"tsx src/blacklang.e2e.matrix.ts --plan\");\n")
		builder.WriteString("assert.equal(packageScripts[\"test:e2e:matrix\"], \"npm run db:generate && tsx src/blacklang.e2e.matrix.ts --run\");\n")
		builder.WriteString("assert.equal(browserMatrixManifest.planCommand, \"npm run test:e2e:plan\");\n")
		builder.WriteString("assert.equal(browserMatrixManifest.runCommand, \"npm run test:e2e:matrix\");\n")
		builder.WriteString("assert.ok(browserMatrixManifest.policy?.includes(\"Plan mode is read-only\"));\n")
		builder.WriteString("assert.ok(browserMatrixTargets.some((target) => target.name === \"chrome\" && target.family === \"chromium\"));\n")
		builder.WriteString("assert.ok(browserMatrixTargets.some((target) => target.name === \"edge\" && target.family === \"chromium\"));\n")
		builder.WriteString("assert.ok(fs.existsSync(path.join(process.cwd(), \"src\", \"blacklang.e2e.matrix.ts\")), \"browser e2e matrix runner should be generated\");\n")
	}
	if g.hasOpsObserve() {
		builder.WriteString(fmt.Sprintf("assert.equal((spec as any)[\"x-blacklang-observability\"]?.provider, %q);\n", g.opsObserveProvider()))
		builder.WriteString(fmt.Sprintf("assert.equal((spec as any)[\"x-blacklang-observability\"]?.endpointEnv, %q);\n", g.opsObserveEndpointEnv()))
		builder.WriteString(fmt.Sprintf("assert.equal((spec as any)[\"x-blacklang-observability\"]?.protocol, %q);\n", g.opsObserveProtocol()))
		builder.WriteString("assert.equal((spec as any)[\"x-blacklang-observability\"]?.traceContext, \"w3c-traceparent\");\n")
		builder.WriteString(fmt.Sprintf("assert.equal(observabilityManifest.provider, %q);\n", g.opsObserveProvider()))
		builder.WriteString(fmt.Sprintf("assert.equal(observabilityManifest.endpointEnv, %q);\n", g.opsObserveEndpointEnv()))
		builder.WriteString(fmt.Sprintf("assert.equal(observabilityManifest.signal, %q);\n", g.opsObserveSignal()))
		builder.WriteString("assert.equal(observabilityManifest.delivery, \"non-blocking\");\n")
		builder.WriteString("assert.equal(observabilityManifest.traceContext, \"w3c-traceparent\");\n")
		builder.WriteString("assert.equal(observabilityManifest.exporter?.nonBlocking, true);\n")
		builder.WriteString("assert.ok(fs.existsSync(path.join(process.cwd(), \"ops\", \"observability.json\")), \"observability manifest should be generated\");\n")
	}
	if g.hasJobs() {
		builder.WriteString(fmt.Sprintf("assert.equal((spec as any)[\"x-blacklang-jobs\"]?.length, %d);\n", len(g.program.Jobs)))
		for _, job := range g.program.Jobs {
			builder.WriteString(fmt.Sprintf("assert.ok((spec as any)[\"x-blacklang-jobs\"].some((item: any) => item.name === %q && item.run === \"query\" && item.query === %q));\n", job.Name, job.Run.Query))
		}
	}
	if g.hasServices() {
		builder.WriteString(fmt.Sprintf("assert.equal((spec as any)[\"x-blacklang-services\"]?.length, %d);\n", len(g.program.Services)))
		builder.WriteString(fmt.Sprintf("assert.equal(serviceItems.length, %d);\n", len(g.program.Services)))
		for _, service := range g.program.Services {
			builder.WriteString(fmt.Sprintf("assert.ok((spec as any).tags?.some((tag: any) => tag.name === %q));\n", service.Name))
			builder.WriteString(fmt.Sprintf("assert.ok(serviceItems.some((item) => item.name === %q && item.apis?.length === %d));\n", service.Name, len(service.APIs)))
		}
	}
	if g.program.Auth != nil {
		builder.WriteString("assertSchema(\"AuthUser\");\n")
		builder.WriteString("assert.equal((schemas[\"AuthUser\"] as any).properties?.roles?.type, \"array\");\n")
		builder.WriteString("assert.equal((schemas[\"AuthUser\"] as any).properties?.roles?.uniqueItems, true);\n")
		if len(g.program.Roles) > 0 {
			builder.WriteString("assertSchema(\"AuthRoleUpdateInput\");\n")
			builder.WriteString("assert.equal((schemas[\"AuthRoleUpdateInput\"] as any).properties?.roles?.type, \"array\");\n")
			builder.WriteString("assert.equal((schemas[\"AuthRoleUpdateInput\"] as any).required?.includes(\"roles\"), true);\n")
			if g.hasTenantPolicies() {
				builder.WriteString("assertSchema(\"AuthTenantUpdateInput\");\n")
				builder.WriteString("assertPath(\"/api/auth/users/{id}/tenant\", \"put\");\n")
				builder.WriteString("assert.equal((schemas[\"AuthTenantUpdateInput\"] as any).properties?.tenantId?.pattern, \"^[A-Za-z0-9_-]+$\");\n")
				builder.WriteString("assert.equal((schemas[\"AuthTenantUpdateInput\"] as any).required?.includes(\"tenantId\"), true);\n")
			}
		}
	}
	builder.WriteString(g.contractOpenAPITests())
	builder.WriteString(g.contractValidationTests())
	builder.WriteString("console.log(\"BlackLang generated contract tests passed\");\n")
	return builder.String()
}

func (g *webGenerator) entitiesWithGeneratedValidation() []EntityDecl {
	sources := map[string]bool{}
	for _, page := range g.program.Pages {
		sources[page.Source] = true
	}
	entities := []EntityDecl{}
	for _, entity := range g.program.Entities {
		if sources[entity.Name] {
			entities = append(entities, entity)
		}
	}
	return entities
}

func (g *webGenerator) contractOpenAPITests() string {
	var builder strings.Builder
	if path := g.opsHealthPath(); path != "" {
		builder.WriteString(fmt.Sprintf("assertPath(%q, \"get\");\n", path))
		builder.WriteString(fmt.Sprintf("assert.equal(paths[%q]?.get?.[\"x-blacklang-ops\"], \"health\");\n", path))
		builder.WriteString(fmt.Sprintf("assert.equal(paths[%q]?.get?.[\"x-blacklang-public\"], true);\n", path))
	}
	if path := g.opsReadinessPath(); path != "" {
		builder.WriteString(fmt.Sprintf("assertPath(%q, \"get\");\n", path))
		builder.WriteString(fmt.Sprintf("assert.equal(paths[%q]?.get?.[\"x-blacklang-ops\"], \"readiness\");\n", path))
		builder.WriteString(fmt.Sprintf("assert.equal(paths[%q]?.get?.[\"x-blacklang-public\"], true);\n", path))
	}
	if path := g.opsMetricsPath(); path != "" {
		builder.WriteString(fmt.Sprintf("assertPath(%q, \"get\");\n", path))
		builder.WriteString(fmt.Sprintf("assert.equal(paths[%q]?.get?.[\"x-blacklang-ops\"], \"metrics\");\n", path))
		builder.WriteString(fmt.Sprintf("assert.equal(paths[%q]?.get?.[\"x-blacklang-public\"], true);\n", path))
	}
	for _, entity := range g.program.Entities {
		builder.WriteString(fmt.Sprintf("assertSchema(%q);\n", entity.Name))
		builder.WriteString(fmt.Sprintf("assertSchema(%q);\n", entity.Name+"Input"))
	}
	for _, action := range g.program.Actions {
		builder.WriteString(fmt.Sprintf("assertSchema(%q);\n", action.Name+"Input"))
		builder.WriteString(fmt.Sprintf("assertSchema(%q);\n", action.Name+"Response"))
	}
	for _, page := range g.program.Pages {
		base := "/api/" + strings.ToLower(page.Name)
		item := base + "/{id}"
		builder.WriteString(fmt.Sprintf("assertPath(%q, \"get\");\n", base))
		builder.WriteString(fmt.Sprintf("assertPath(%q, \"get\");\n", item))
		if hasAction(page, "create") {
			builder.WriteString(fmt.Sprintf("assertPath(%q, \"post\");\n", base))
		}
		if hasAction(page, "edit") {
			builder.WriteString(fmt.Sprintf("assertPath(%q, \"put\");\n", item))
		}
		if hasAction(page, "delete") {
			builder.WriteString(fmt.Sprintf("assertPath(%q, \"delete\");\n", item))
		}
		if hasAction(page, "archive") {
			builder.WriteString(fmt.Sprintf("assertPath(%q, \"patch\");\n", item+"/archive"))
		}
		if hasAction(page, "restore") {
			builder.WriteString(fmt.Sprintf("assertPath(%q, \"patch\");\n", item+"/restore"))
		}
		if page.Query != "" {
			builder.WriteString(fmt.Sprintf("assertPath(%q, \"get\");\n", base+"/query"))
			if query, ok := findQuery(g.program, page.Query); ok && len(query.Aggregates) > 0 {
				builder.WriteString(fmt.Sprintf("assertPath(%q, \"get\");\n", base+"/query/summary"))
				builder.WriteString(fmt.Sprintf("assert.equal(paths[%q]?.get?.[\"x-blacklang-query-summary\"], %q);\n", base+"/query/summary", query.Name))
				builder.WriteString(fmt.Sprintf("assert.equal(paths[%q]?.get?.[\"x-blacklang-aggregates\"]?.length, %d);\n", base+"/query/summary", len(query.Aggregates)))
			}
		}
		for _, action := range customActionsForPage(g.program, page) {
			builder.WriteString(fmt.Sprintf("assertPath(%q, \"post\");\n", item+"/actions/"+strings.ToLower(action.Name)))
			builder.WriteString(fmt.Sprintf("assert.equal(paths[%q]?.post?.[\"x-blacklang-action\"], %q);\n", item+"/actions/"+strings.ToLower(action.Name), action.Name))
			if transactionName, transactional := g.customActionTransactionName(action); transactional {
				builder.WriteString(fmt.Sprintf("assert.equal(paths[%q]?.post?.[\"x-blacklang-transaction\"], true);\n", item+"/actions/"+strings.ToLower(action.Name)))
				if transactionName != "" {
					builder.WriteString(fmt.Sprintf("assert.equal(paths[%q]?.post?.[\"x-blacklang-transaction-name\"], %q);\n", item+"/actions/"+strings.ToLower(action.Name), transactionName))
				}
			}
		}
	}
	for _, api := range g.program.APIs {
		if api.Method != "" && api.Path != "" {
			method := strings.ToLower(api.Method)
			builder.WriteString(fmt.Sprintf("assertPath(%q, %q);\n", api.Path, method))
			builder.WriteString(fmt.Sprintf("assert.equal(paths[%q]?.%s?.[\"x-blacklang-api\"], %q);\n", api.Path, method, api.Name))
			builder.WriteString(fmt.Sprintf("assert.equal(paths[%q]?.%s?.[\"x-blacklang-runtime\"], \"declared\");\n", api.Path, method))
			if api.Webhook {
				builder.WriteString(fmt.Sprintf("assert.equal(paths[%q]?.%s?.[\"x-blacklang-webhook\"], true);\n", api.Path, method))
			}
			if api.Update != nil {
				builder.WriteString(fmt.Sprintf("assert.equal(paths[%q]?.%s?.[\"x-blacklang-handler\"], \"update\");\n", api.Path, method))
				builder.WriteString(fmt.Sprintf("assert.equal(paths[%q]?.%s?.[\"x-blacklang-update\"]?.source, %q);\n", api.Path, method, api.Update.Source))
			}
			if transactionName, transactional := g.explicitAPITransactionName(api); transactional {
				builder.WriteString(fmt.Sprintf("assert.equal(paths[%q]?.%s?.[\"x-blacklang-transaction\"], true);\n", api.Path, method))
				if transactionName != "" {
					builder.WriteString(fmt.Sprintf("assert.equal(paths[%q]?.%s?.[\"x-blacklang-transaction-name\"], %q);\n", api.Path, method, transactionName))
				}
			}
			if serviceName, ok := g.explicitAPIServiceName(api); ok {
				builder.WriteString(fmt.Sprintf("assert.equal(paths[%q]?.%s?.[\"x-blacklang-service\"], %q);\n", api.Path, method, serviceName))
				builder.WriteString(fmt.Sprintf("assert.equal(paths[%q]?.%s?.tags?.includes(%q), true);\n", api.Path, method, serviceName))
			}
		}
	}
	builder.WriteString("\n")
	return builder.String()
}

func (g *webGenerator) contractValidationTests() string {
	var builder strings.Builder
	for _, entity := range g.entitiesWithGeneratedValidation() {
		validName := "valid" + entity.Name + "Input"
		builder.WriteString(fmt.Sprintf("const %s: Record<string, unknown> = %s;\n", validName, g.contractEntityInputLiteral(entity)))
		builder.WriteString(fmt.Sprintf("assertValid(validate%sInput(%s), %q);\n", entity.Name, validName, entity.Name+" valid input"))
		for _, field := range entity.Fields {
			inputName := g.contractInputFieldName(entity, field)
			if hasModifier(field, "required") && modifierValue(field, "default") == "" {
				missingName := lowerCamelCase(entity.Name) + "Missing" + title(field.Name)
				builder.WriteString(fmt.Sprintf("const %s: Record<string, unknown> = { ...%s };\n", missingName, validName))
				builder.WriteString(fmt.Sprintf("delete %s[%q];\n", missingName, inputName))
				builder.WriteString(fmt.Sprintf("assertInvalid(validate%sInput(%s), %q);\n", entity.Name, missingName, entity.Name+" missing "+inputName))
			}
			if field.Type == "number" || field.Type == "integer" {
				fractionalName := lowerCamelCase(entity.Name) + "Fractional" + title(field.Name)
				builder.WriteString(fmt.Sprintf("const %s: Record<string, unknown> = { ...%s, %s: 1.5 };\n", fractionalName, validName, inputName))
				builder.WriteString(fmt.Sprintf("assertInvalid(validate%sInput(%s), %q);\n", entity.Name, fractionalName, entity.Name+" fractional "+inputName))
			}
		}
		for _, action := range customActionsForEntity(g.program, entity.Name) {
			validAction := "valid" + action.Name + "Input"
			builder.WriteString(fmt.Sprintf("const %s: Record<string, unknown> = %s;\n", validAction, contractActionInputLiteral(action)))
			builder.WriteString(fmt.Sprintf("assertValid(validate%sInput(%s), %q);\n", action.Name, validAction, action.Name+" valid input"))
			for _, input := range action.Inputs {
				if hasModifier(input, "required") && modifierValue(input, "default") == "" {
					missingName := lowerCamelCase(action.Name) + "Missing" + title(input.Name)
					builder.WriteString(fmt.Sprintf("const %s: Record<string, unknown> = { ...%s };\n", missingName, validAction))
					builder.WriteString(fmt.Sprintf("delete %s[%q];\n", missingName, input.Name))
					builder.WriteString(fmt.Sprintf("assertInvalid(validate%sInput(%s), %q);\n", action.Name, missingName, action.Name+" missing "+input.Name))
				}
				if input.Type == "number" || input.Type == "integer" {
					fractionalName := lowerCamelCase(action.Name) + "Fractional" + title(input.Name)
					builder.WriteString(fmt.Sprintf("const %s: Record<string, unknown> = { ...%s, %s: 1.5 };\n", fractionalName, validAction, input.Name))
					builder.WriteString(fmt.Sprintf("assertInvalid(validate%sInput(%s), %q);\n", action.Name, fractionalName, action.Name+" fractional "+input.Name))
				}
				if minValue := modifierValue(input, "min"); minValue != "" && (input.Type == "number" || input.Type == "integer" || input.Type == "decimal" || input.Type == "money") {
					if invalid, ok := contractBelowMinLiteral(minValue); ok {
						minName := lowerCamelCase(action.Name) + "BelowMin" + title(input.Name)
						builder.WriteString(fmt.Sprintf("const %s: Record<string, unknown> = { ...%s, %s: %s };\n", minName, validAction, input.Name, invalid))
						builder.WriteString(fmt.Sprintf("assertInvalid(validate%sInput(%s), %q);\n", action.Name, minName, action.Name+" below min "+input.Name))
					}
				}
			}
		}
		builder.WriteString("\n")
	}
	return builder.String()
}

func (g *webGenerator) contractEntityInputLiteral(entity EntityDecl) string {
	parts := []string{}
	for _, field := range entity.Fields {
		inputName := g.contractInputFieldName(entity, field)
		parts = append(parts, fmt.Sprintf("%s: %s", inputName, contractFieldValueLiteral(field)))
	}
	return "{ " + strings.Join(parts, ", ") + " }"
}

func (g *webGenerator) contractInputFieldName(entity EntityDecl, field FieldDecl) string {
	if g.isRelationField(field) {
		return relationIDFieldName(field)
	}
	return field.Name
}

func contractActionInputLiteral(action CustomActionDecl) string {
	parts := []string{}
	for _, input := range action.Inputs {
		parts = append(parts, fmt.Sprintf("%s: %s", input.Name, contractFieldValueLiteral(input)))
	}
	return "{ " + strings.Join(parts, ", ") + " }"
}

func contractFieldValueLiteral(field FieldDecl) string {
	switch field.Type {
	case "email":
		return contractJSONString(contractStringValue(field, "agent@example.com"))
	case "number", "integer":
		return contractIntegerValue(field)
	case "decimal", "money":
		return contractDecimalValue(field)
	case "boolean":
		return "true"
	case "date":
		return `"2026-09-06"`
	case "datetime":
		return `"2026-09-06T12:00:00Z"`
	case "file":
		return `"data:application/octet-stream;base64,AA=="`
	case "image":
		return `"data:image/png;base64,AA=="`
	default:
		if hasModifier(field, "url") {
			return contractJSONString(contractStringValue(field, "https://example.com"))
		}
		return contractJSONString(contractStringValue(field, "Sample"))
	}
}

func contractStringValue(field FieldDecl, fallback string) string {
	value := fallback
	if pattern := modifierValue(field, "regex"); pattern != "" {
		if strings.Contains(pattern, "A-Z") || strings.Contains(pattern, "\\d") || strings.Contains(pattern, "0-9") {
			value = "ABC123"
		}
	}
	if minLength, maxLength, ok := fieldLengthBounds(field); ok {
		target := minLength
		if target < 1 {
			target = 1
		}
		if target > maxLength {
			target = maxLength
		}
		if target > 0 {
			value = strings.Repeat("A", target)
		}
	}
	return value
}

func contractIntegerValue(field FieldDecl) string {
	value := 1.0
	if minValue, ok := contractNumericModifier(field, "min"); ok && value < minValue {
		value = math.Ceil(minValue)
	}
	if maxValue, ok := contractNumericModifier(field, "max"); ok && value > maxValue {
		value = math.Floor(maxValue)
	}
	return strconv.FormatInt(int64(value), 10)
}

func contractDecimalValue(field FieldDecl) string {
	value := 1.25
	if minValue, ok := contractNumericModifier(field, "min"); ok && value < minValue {
		value = minValue
	}
	if maxValue, ok := contractNumericModifier(field, "max"); ok && value > maxValue {
		value = maxValue
	}
	return strconv.FormatFloat(value, 'f', -1, 64)
}

func contractNumericModifier(field FieldDecl, name string) (float64, bool) {
	value := modifierValue(field, name)
	if value == "" {
		return 0, false
	}
	parsed, err := strconv.ParseFloat(value, 64)
	return parsed, err == nil && !math.IsInf(parsed, 0) && !math.IsNaN(parsed)
}

func contractBelowMinLiteral(value string) (string, bool) {
	parsed, err := strconv.ParseFloat(value, 64)
	if err != nil || math.IsInf(parsed, 0) || math.IsNaN(parsed) {
		return "", false
	}
	return strconv.FormatFloat(parsed-1, 'f', -1, 64), true
}

func contractJSONString(value string) string {
	encoded, _ := json.Marshal(value)
	return string(encoded)
}
