package main

import (
	"encoding/json"
	"fmt"
	"path/filepath"
	"strings"
)

type generatedServiceManifest struct {
	Version  string                 `json:"version"`
	App      string                 `json:"app"`
	Services []generatedServiceItem `json:"services"`
}

type generatedServiceItem struct {
	Name string                `json:"name"`
	APIs []generatedServiceAPI `json:"apis"`
}

type generatedServiceAPI struct {
	Name        string `json:"name"`
	Method      string `json:"method"`
	Path        string `json:"path"`
	Access      string `json:"access"`
	Runtime     string `json:"runtime"`
	Handler     string `json:"handler,omitempty"`
	Webhook     bool   `json:"webhook,omitempty"`
	Transaction string `json:"transaction,omitempty"`
}

func (g *webGenerator) hasServices() bool {
	return len(g.program.Services) > 0
}

func (g *webGenerator) serviceManifestJSON() string {
	content, err := json.MarshalIndent(g.generatedServiceManifest(), "", "  ")
	if err != nil {
		return "{\n  \"version\": \"0.1.0\",\n  \"services\": []\n}\n"
	}
	return string(content) + "\n"
}

func (g *webGenerator) generatedServiceManifest() generatedServiceManifest {
	services := []generatedServiceItem{}
	for _, service := range g.program.Services {
		services = append(services, generatedServiceItem{
			Name: service.Name,
			APIs: g.generatedServiceAPIs(service),
		})
	}
	return generatedServiceManifest{
		Version:  "0.1.0",
		App:      g.program.App.Name,
		Services: services,
	}
}

func (g *webGenerator) generatedServiceAPIs(service ServiceDecl) []generatedServiceAPI {
	apis := []generatedServiceAPI{}
	for _, target := range service.APIs {
		api, ok := g.findAPI(target.Name)
		if !ok {
			continue
		}
		item := generatedServiceAPI{
			Name:    api.Name,
			Method:  strings.ToUpper(api.Method),
			Path:    api.Path,
			Access:  explicitAPIAccess(api),
			Runtime: "declared",
			Webhook: api.Webhook,
		}
		if api.Update != nil {
			item.Handler = "update"
		} else {
			item.Handler = "declared"
		}
		if transactionName, ok := g.explicitAPITransactionName(api); ok {
			item.Transaction = transactionName
		}
		apis = append(apis, item)
	}
	return apis
}

func (g *webGenerator) serviceModuleTS(service ServiceDecl) string {
	contentBytes, err := json.MarshalIndent(generatedServiceItem{
		Name: service.Name,
		APIs: g.generatedServiceAPIs(service),
	}, "", "  ")
	content := string(contentBytes)
	if err != nil {
		content = fmt.Sprintf("{\n  \"name\": %s,\n  \"apis\": []\n}", contractJSONString(service.Name))
	}
	constName := lowerCamelCase(service.Name) + "Service"
	typeName := service.Name + "APIName"
	var builder strings.Builder
	builder.WriteString("// Generated by BlackLang. Do not edit manually.\n\n")
	builder.WriteString(fmt.Sprintf("export const %s = ", constName))
	builder.WriteString(content)
	builder.WriteString(" as const;\n\n")
	builder.WriteString(fmt.Sprintf("export type %s = typeof %s.apis[number][\"name\"];\n", typeName, constName))
	return builder.String()
}

func (g *webGenerator) serviceGeneratedFiles() []GeneratedFile {
	files := []GeneratedFile{}
	if !g.hasServices() {
		return files
	}
	files = append(files, GeneratedFile{Path: filepath.Join(g.outDir, "services", "manifest.json"), Kind: "service-manifest"})
	for _, service := range g.program.Services {
		files = append(files, GeneratedFile{Path: filepath.Join(g.outDir, "src", "services", kebabCase(service.Name)+".ts"), Kind: "service-module"})
	}
	return files
}

func (g *webGenerator) findAPI(name string) (APIDecl, bool) {
	for _, api := range g.program.APIs {
		if api.Name == name {
			return api, true
		}
	}
	return APIDecl{}, false
}

func (g *webGenerator) openapiServiceTags() []any {
	tags := []any{}
	for _, service := range g.program.Services {
		tags = append(tags, map[string]any{
			"name":        service.Name,
			"description": "BlackLang service module for explicit API declarations.",
		})
	}
	return tags
}

func (g *webGenerator) openapiServicesMetadata() []any {
	metadata := []any{}
	for _, service := range g.generatedServiceManifest().Services {
		metadata = append(metadata, map[string]any{
			"name": service.Name,
			"apis": service.APIs,
		})
	}
	return metadata
}
