package main

import (
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
)

type generatedSeedRow struct {
	Seed    string        `json:"seed"`
	Entity  string        `json:"entity"`
	Model   string        `json:"model"`
	Table   string        `json:"table"`
	Key     string        `json:"key"`
	Columns []string      `json:"columns"`
	Types   []string      `json:"types"`
	Values  []interface{} `json:"values"`
}

func (g *webGenerator) hasSeeds() bool {
	return len(g.program.Seeds) > 0
}

func (g *webGenerator) seedTS() string {
	if g.isPostgres() {
		return g.postgresSeedTS()
	}
	if g.isMySQL() {
		return g.mysqlSeedTS()
	}
	return g.sqliteSeedTS()
}

func (g *webGenerator) seedRowsLiteral() string {
	rows := []generatedSeedRow{}
	for _, seed := range g.program.Seeds {
		entity, ok := g.findEntity(seed.Source)
		if !ok {
			continue
		}
		for _, row := range seed.Rows {
			generated := generatedSeedRow{
				Seed:    seed.Name,
				Entity:  entity.Name,
				Model:   lowerCamelCase(entity.Name),
				Table:   entity.Name,
				Key:     row.Key,
				Columns: []string{},
				Types:   []string{},
				Values:  []interface{}{},
			}
			for _, value := range row.Values {
				field, ok := findField(entity, value.Field)
				if !ok {
					continue
				}
				generated.Columns = append(generated.Columns, g.sqliteColumnName(field))
				generated.Types = append(generated.Types, field.Type)
				generated.Values = append(generated.Values, g.seedRuntimeValue(field, value.Value))
			}
			rows = append(rows, generated)
		}
	}
	content, err := json.MarshalIndent(rows, "", "  ")
	if err != nil {
		return "[]"
	}
	return string(content)
}

func (g *webGenerator) seedRuntimeValue(field FieldDecl, value SeedLiteral) interface{} {
	if value.Kind == "ref" {
		return value.Value
	}
	switch value.Kind {
	case "number":
		if strings.Contains(value.Value, ".") {
			parsed, err := strconv.ParseFloat(value.Value, 64)
			if err == nil {
				return parsed
			}
			return value.Value
		}
		parsed, err := strconv.Atoi(value.Value)
		if err == nil {
			return parsed
		}
		return value.Value
	case "boolean":
		if g.isPostgres() || g.isMySQL() {
			return value.Value == "true"
		}
		if value.Value == "true" {
			return 1
		}
		return 0
	default:
		_ = field
		return value.Value
	}
}

func (g *webGenerator) sqliteSeedTS() string {
	return fmt.Sprintf(`// Generated by BlackLang. Do not edit manually.

import "dotenv/config";
import Database from "better-sqlite3";

type SeedRow = {
  seed: string;
  entity: string;
  model: string;
  table: string;
  key: string;
  columns: string[];
  types: string[];
  values: unknown[];
};

const seedRows: SeedRow[] = %s;

const databaseUrl = %s ?? "file:./dev.db";
const filePath = databaseUrl.startsWith("file:") ? databaseUrl.slice(5) : databaseUrl;
const db = new Database(filePath);

function quoteIdentifier(value: string): string {
  return '"' + value.replace(/"/g, '""') + '"';
}

function applySeedRow(row: SeedRow): void {
  const columns = ["id", ...row.columns];
  const quotedColumns = columns.map(quoteIdentifier).join(", ");
  const placeholders = columns.map(() => "?").join(", ");
  const assignments = row.columns.map((column) => quoteIdentifier(column) + " = excluded." + quoteIdentifier(column));
  assignments.push('"updatedAt" = CURRENT_TIMESTAMP');
  const sql = "INSERT INTO " + quoteIdentifier(row.table) + " (" + quotedColumns + ") VALUES (" + placeholders + ") ON CONFLICT(\"id\") DO UPDATE SET " + assignments.join(", ");
  db.prepare(sql).run(row.key, ...row.values);
}

const applySeeds = db.transaction(() => {
  for (const row of seedRows) {
    applySeedRow(row);
  }
});

applySeeds();
db.close();

console.log("BlackLang seed data applied: " + seedRows.length + " rows");
`, g.seedRowsLiteral(), g.databaseEnvAccess())
}

func (g *webGenerator) postgresSeedTS() string {
	return fmt.Sprintf(`// Generated by BlackLang. Do not edit manually.

import "dotenv/config";
import pg from "pg";

type SeedRow = {
  seed: string;
  entity: string;
  model: string;
  table: string;
  key: string;
  columns: string[];
  types: string[];
  values: unknown[];
};

const seedRows: SeedRow[] = %s;

const databaseUrl = %s ?? %q;

function quoteIdentifier(value: string): string {
  return '"' + value.replace(/"/g, '""') + '"';
}

async function applySeedRow(client: pg.Client, row: SeedRow): Promise<void> {
  const columns = ["id", ...row.columns];
  const quotedColumns = columns.map(quoteIdentifier).join(", ");
  const placeholders = columns.map((_column, index) => "$" + (index + 1)).join(", ");
  const assignments = row.columns.map((column) => quoteIdentifier(column) + " = EXCLUDED." + quoteIdentifier(column));
  assignments.push('"updatedAt" = CURRENT_TIMESTAMP');
  const sql = "INSERT INTO " + quoteIdentifier(row.table) + " (" + quotedColumns + ") VALUES (" + placeholders + ") ON CONFLICT (\"id\") DO UPDATE SET " + assignments.join(", ");
  await client.query(sql, [row.key, ...row.values]);
}

async function main(): Promise<void> {
  const client = new pg.Client({ connectionString: databaseUrl });
  await client.connect();
  try {
    await client.query("BEGIN");
    for (const row of seedRows) {
      await applySeedRow(client, row);
    }
    await client.query("COMMIT");
  } catch (error) {
    await client.query("ROLLBACK");
    throw error;
  } finally {
    await client.end();
  }
  console.log("BlackLang seed data applied: " + seedRows.length + " rows");
}

void main().catch((error) => {
  console.error(error);
  process.exit(1);
});
`, g.seedRowsLiteral(), g.databaseEnvAccess(), g.defaultDatabaseURL())
}

func (g *webGenerator) mysqlSeedTS() string {
	return fmt.Sprintf(`// Generated by BlackLang. Do not edit manually.

import "dotenv/config";
import { prisma } from "./db";

type SeedRow = {
  seed: string;
  entity: string;
  model: string;
  table: string;
  key: string;
  columns: string[];
  types: string[];
  values: unknown[];
};

type PrismaModelDelegate = {
  upsert(args: {
    where: { id: string };
    create: Record<string, unknown>;
    update: Record<string, unknown>;
  }): Promise<unknown>;
};

const seedRows: SeedRow[] = %s;

function modelDelegate(row: SeedRow): PrismaModelDelegate {
  const delegate = (prisma as unknown as Record<string, PrismaModelDelegate | undefined>)[row.model];
  if (!delegate) {
    throw new Error("Unknown Prisma model delegate for seed " + row.seed + " entity " + row.entity);
  }
  return delegate;
}

function coerceSeedValue(type: string, value: unknown): unknown {
  if ((type === "date" || type === "datetime") && typeof value === "string") {
    return new Date(value);
  }
  return value;
}

function rowData(row: SeedRow): Record<string, unknown> {
  const data: Record<string, unknown> = { id: row.key };
  row.columns.forEach((column, index) => {
    data[column] = coerceSeedValue(row.types[index] ?? "", row.values[index]);
  });
  return data;
}

function updateData(data: Record<string, unknown>): Record<string, unknown> {
  const update = { ...data };
  delete update.id;
  return update;
}

async function main(): Promise<void> {
  for (const row of seedRows) {
    const data = rowData(row);
    await modelDelegate(row).upsert({
      where: { id: row.key },
      create: data,
      update: updateData(data)
    });
  }
  await prisma.$disconnect();
  console.log("BlackLang seed data applied: " + seedRows.length + " rows");
}

void main().catch(async (error) => {
  await prisma.$disconnect().catch(() => undefined);
  console.error(error);
  process.exit(1);
});
`, g.seedRowsLiteral())
}
