package main

import (
	"encoding/json"
	"fmt"
	"strings"
)

type generatedJobManifest struct {
	Version string         `json:"version"`
	App     string         `json:"app"`
	Target  string         `json:"target"`
	Runtime string         `json:"runtime"`
	Jobs    []generatedJob `json:"jobs"`
}

type generatedJob struct {
	Name       string   `json:"name"`
	Schedule   string   `json:"schedule"`
	Every      int      `json:"every"`
	Unit       string   `json:"unit"`
	IntervalMs int      `json:"intervalMs"`
	Run        string   `json:"run"`
	Query      string   `json:"query,omitempty"`
	Source     string   `json:"source,omitempty"`
	Limit      int      `json:"limit,omitempty"`
	Steps      []string `json:"steps"`
}

func (g *webGenerator) hasJobs() bool {
	return len(g.program.Jobs) > 0
}

func (g *webGenerator) generatedJobs() []generatedJob {
	jobs := []generatedJob{}
	for _, job := range g.program.Jobs {
		generated := generatedJob{
			Name:       job.Name,
			Schedule:   jobScheduleLabel(job),
			Every:      job.Schedule.Every,
			Unit:       job.Schedule.Unit,
			IntervalMs: jobIntervalMs(job),
			Run:        job.Run.Kind,
			Query:      job.Run.Query,
			Steps: []string{
				"Run npm run jobs:run for one deterministic execution.",
				"Run npm run jobs:loop to keep the generated worker alive on the declared schedule.",
				"Keep queue providers, retries, mutating jobs, and external schedulers outside the core MVP.",
			},
		}
		if job.Run.Kind == "query" {
			if query, ok := findQuery(g.program, job.Run.Query); ok {
				generated.Source = query.Source
				generated.Limit = effectiveQueryLimit(query)
			}
		}
		jobs = append(jobs, generated)
	}
	return jobs
}

func (g *webGenerator) jobsManifestJSON() string {
	data, err := json.MarshalIndent(generatedJobManifest{
		Version: version,
		App:     g.program.App.Name,
		Target:  g.targetName(),
		Runtime: "node-worker",
		Jobs:    g.generatedJobs(),
	}, "", "  ")
	if err != nil {
		return "{}\n"
	}
	return string(data) + "\n"
}

func (g *webGenerator) workerTS() string {
	var builder strings.Builder
	builder.WriteString("// Generated by BlackLang. Do not edit manually.\n\n")
	builder.WriteString("import \"dotenv/config\";\n")
	builder.WriteString("import { pathToFileURL } from \"node:url\";\n")
	builder.WriteString("import { prisma } from \"./db\";\n\n")
	builder.WriteString("type BlackJob = {\n")
	builder.WriteString("  name: string;\n")
	builder.WriteString("  schedule: string;\n")
	builder.WriteString("  every: number;\n")
	builder.WriteString("  unit: \"minutes\" | \"hours\" | \"days\";\n")
	builder.WriteString("  intervalMs: number;\n")
	builder.WriteString("  run: \"query\";\n")
	builder.WriteString("  query: string;\n")
	builder.WriteString("  source: string;\n")
	builder.WriteString("  limit: number;\n")
	builder.WriteString("  steps: string[];\n")
	builder.WriteString("};\n\n")
	builder.WriteString("type JobRunResult = {\n")
	builder.WriteString("  job: string;\n")
	builder.WriteString("  schedule: string;\n")
	builder.WriteString("  run: \"query\";\n")
	builder.WriteString("  query: string;\n")
	builder.WriteString("  source: string;\n")
	builder.WriteString("  count: number;\n")
	builder.WriteString("  limit: number;\n")
	builder.WriteString("  at: string;\n")
	builder.WriteString("};\n\n")
	builder.WriteString("export const blackJobs: BlackJob[] = ")
	data, err := json.MarshalIndent(g.generatedJobs(), "", "  ")
	if err != nil {
		data = []byte("[]")
	}
	builder.Write(data)
	builder.WriteString(" as BlackJob[];\n\n")
	for _, job := range g.program.Jobs {
		builder.WriteString(g.jobRunnerFunction(job))
	}
	builder.WriteString("export async function runJob(name: string): Promise<JobRunResult> {\n")
	builder.WriteString("  switch (name) {\n")
	for _, job := range g.program.Jobs {
		builder.WriteString(fmt.Sprintf("    case %q:\n", job.Name))
		builder.WriteString(fmt.Sprintf("      return %s();\n", jobRunnerFunctionName(job)))
	}
	builder.WriteString("    default:\n")
	builder.WriteString("      throw new Error(\"Unknown BlackLang job \" + name);\n")
	builder.WriteString("  }\n")
	builder.WriteString("}\n\n")
	builder.WriteString("export async function runAllJobsOnce() {\n")
	builder.WriteString("  const results: JobRunResult[] = [];\n")
	builder.WriteString("  for (const job of blackJobs) {\n")
	builder.WriteString("    results.push(await runJob(job.name));\n")
	builder.WriteString("  }\n")
	builder.WriteString("  return results;\n")
	builder.WriteString("}\n\n")
	builder.WriteString("function selectedJobName() {\n")
	builder.WriteString("  const index = process.argv.indexOf(\"--job\");\n")
	builder.WriteString("  return index >= 0 ? process.argv[index + 1] ?? \"\" : \"\";\n")
	builder.WriteString("}\n\n")
	builder.WriteString("async function runSelectedJobsOnce() {\n")
	builder.WriteString("  const selected = selectedJobName();\n")
	builder.WriteString("  if (selected) {\n")
	builder.WriteString("    return [await runJob(selected)];\n")
	builder.WriteString("  }\n")
	builder.WriteString("  return runAllJobsOnce();\n")
	builder.WriteString("}\n\n")
	builder.WriteString("async function loopJobs() {\n")
	builder.WriteString("  const selected = selectedJobName();\n")
	builder.WriteString("  const jobs = selected ? blackJobs.filter((job) => job.name === selected) : blackJobs;\n")
	builder.WriteString("  if (selected && jobs.length === 0) throw new Error(\"Unknown BlackLang job \" + selected);\n")
	builder.WriteString("  await Promise.all(jobs.map((job) => runJob(job.name)));\n")
	builder.WriteString("  for (const job of jobs) {\n")
	builder.WriteString("    setInterval(() => {\n")
	builder.WriteString("      void runJob(job.name).catch((error: unknown) => {\n")
	builder.WriteString("        console.error(JSON.stringify({ job: job.name, status: \"error\", message: error instanceof Error ? error.message : String(error), at: new Date().toISOString() }));\n")
	builder.WriteString("      });\n")
	builder.WriteString("    }, job.intervalMs);\n")
	builder.WriteString("  }\n")
	builder.WriteString("}\n\n")
	builder.WriteString("async function main() {\n")
	builder.WriteString("  if (process.argv.includes(\"--loop\")) {\n")
	builder.WriteString("    await loopJobs();\n")
	builder.WriteString("    return;\n")
	builder.WriteString("  }\n")
	builder.WriteString("  await runSelectedJobsOnce();\n")
	builder.WriteString("  await prisma.$disconnect();\n")
	builder.WriteString("}\n\n")
	builder.WriteString("const isMain = process.argv[1] ? import.meta.url === pathToFileURL(process.argv[1]).href : false;\n")
	builder.WriteString("if (isMain) {\n")
	builder.WriteString("  main().catch(async (error: unknown) => {\n")
	builder.WriteString("    console.error(JSON.stringify({ status: \"error\", message: error instanceof Error ? error.message : String(error), at: new Date().toISOString() }));\n")
	builder.WriteString("    await prisma.$disconnect();\n")
	builder.WriteString("    process.exit(1);\n")
	builder.WriteString("  });\n")
	builder.WriteString("}\n")
	return builder.String()
}

func (g *webGenerator) jobRunnerFunction(job JobDecl) string {
	if job.Run.Kind != "query" {
		return ""
	}
	query, ok := findQuery(g.program, job.Run.Query)
	if !ok {
		return ""
	}
	entity, ok := g.findEntity(query.Source)
	if !ok {
		return ""
	}
	identifier := lowerCamelCase(entity.Name)
	var builder strings.Builder
	builder.WriteString(fmt.Sprintf("async function %s(): Promise<JobRunResult> {\n", jobRunnerFunctionName(job)))
	builder.WriteString("  const items = await prisma." + identifier + ".findMany({\n")
	builder.WriteString("    where: { AND: [\n")
	builder.WriteString("      { archivedAt: null },\n")
	for _, filter := range query.Where {
		field, _ := findField(entity, filter.Field)
		builder.WriteString(fmt.Sprintf("      { [%q]: { %s: %s } },\n", filter.Field, queryPrismaOperator(filter.Operator), queryPrismaLiteral(filter.Value, field)))
	}
	builder.WriteString("    ] },\n")
	builder.WriteString("    orderBy: [")
	if query.Sort.Field != "" {
		builder.WriteString(fmt.Sprintf("{ [%q]: %q }, ", query.Sort.Field, query.Sort.Direction))
	}
	builder.WriteString("{ id: \"asc\" }],\n")
	builder.WriteString(fmt.Sprintf("    take: %d,\n", effectiveQueryLimit(query)))
	builder.WriteString("    select: { id: true }\n")
	builder.WriteString("  });\n")
	builder.WriteString("  const result: JobRunResult = {\n")
	builder.WriteString(fmt.Sprintf("    job: %q,\n", job.Name))
	builder.WriteString(fmt.Sprintf("    schedule: %q,\n", jobScheduleLabel(job)))
	builder.WriteString("    run: \"query\",\n")
	builder.WriteString(fmt.Sprintf("    query: %q,\n", query.Name))
	builder.WriteString(fmt.Sprintf("    source: %q,\n", query.Source))
	builder.WriteString("    count: items.length,\n")
	builder.WriteString(fmt.Sprintf("    limit: %d,\n", effectiveQueryLimit(query)))
	builder.WriteString("    at: new Date().toISOString()\n")
	builder.WriteString("  };\n")
	builder.WriteString("  console.log(JSON.stringify(result));\n")
	builder.WriteString("  return result;\n")
	builder.WriteString("}\n\n")
	return builder.String()
}

func jobRunnerFunctionName(job JobDecl) string {
	return lowerCamelCase(job.Name) + "Job"
}

func jobIntervalMs(job JobDecl) int {
	switch job.Schedule.Unit {
	case "minutes":
		return job.Schedule.Every * 60 * 1000
	case "hours":
		return job.Schedule.Every * 60 * 60 * 1000
	case "days":
		return job.Schedule.Every * 24 * 60 * 60 * 1000
	default:
		return 0
	}
}

func (g *webGenerator) packageJobScripts() string {
	if !g.hasJobs() {
		return ""
	}
	return `,
    "jobs:run": "npm run db:setup && tsx src/worker.ts --once",
    "jobs:loop": "npm run db:setup && tsx src/worker.ts --loop"`
}

func (g *webGenerator) jobsReadmeSection() string {
	if !g.hasJobs() {
		return ""
	}
	return `## Background Jobs

Declared jobs generate jobs/manifest.json, src/worker.ts, and package scripts.

~~~bash
npm run jobs:run
npm run jobs:loop
~~~

`
}

func (g *webGenerator) openapiJobsMetadata() []map[string]any {
	jobs := []map[string]any{}
	for _, job := range g.generatedJobs() {
		jobs = append(jobs, map[string]any{
			"name":       job.Name,
			"schedule":   job.Schedule,
			"every":      job.Every,
			"unit":       job.Unit,
			"intervalMs": job.IntervalMs,
			"run":        job.Run,
			"query":      job.Query,
			"source":     job.Source,
			"limit":      job.Limit,
		})
	}
	return jobs
}
