package main

import "fmt"

func (g *webGenerator) packageMigrationScripts() string {
	if len(g.program.Migrations) == 0 {
		return ""
	}
	return `
    "db:migrate:plan": "tsx src/migrate.ts --plan",
    "db:migrate": "tsx src/migrate.ts --apply",`
}

func (g *webGenerator) migrationReadmeSection() string {
	if len(g.program.Migrations) == 0 {
		return ""
	}
	return `## Migrations

Declared migration blocks generate a read-only online plan and an explicit apply runner.

~~~bash
npm run db:migrate:plan
npm run db:migrate
npm run db:setup
~~~

Run the plan command before applying migrations in CI, VPS, or production-like databases.

`
}

func (g *webGenerator) migrationRunnerTS() string {
	if g.isPostgres() {
		return g.postgresMigrationRunnerTS()
	}
	if g.isMySQL() {
		return g.mysqlUnsupportedMigrationRunnerTS()
	}
	return g.sqliteMigrationRunnerTS()
}

func (g *webGenerator) mysqlUnsupportedMigrationRunnerTS() string {
	return fmt.Sprintf(`// Generated by BlackLang. Do not edit manually.

const appName = %q;
const targetDatabase = "mysql";
const databaseEnvName = %q;
const blackMigrations = %s;
const mode: "plan" | "apply" = process.argv.includes("--apply") ? "apply" : "plan";

console.log(JSON.stringify({
  success: false,
  command: mode === "apply" ? "db:migrate" : "db:migrate:plan",
  mode,
  app: appName,
  targetDatabase,
  databaseEnv: databaseEnvName,
  databaseConfigured: Boolean(process.env[databaseEnvName]),
  databaseReachable: false,
  ready: false,
  summary: {
    total: blackMigrations.length,
    applied: 0,
    pending: blackMigrations.length,
    unsafe: blackMigrations.length
  },
  migrations: blackMigrations.map((migration: { name: string; file: string; operations: unknown[] }) => ({
    name: migration.name,
    file: migration.file,
    operations: migration.operations.length,
    applied: false,
    pending: true,
    safeToApply: false,
    checks: [{
      kind: "target-database",
      target: "mysql",
      status: "unsupported",
      reason: "Generated rename migration runtime for target database mysql is not supported yet."
    }]
  })),
  applied: [],
  skipped: [],
  errors: ["UNSUPPORTED_TARGET_DATABASE_MIGRATION"],
  steps: [
    "Use target database sqlite or postgres for generated rename migration runtime.",
    "Or remove migration blocks before targeting mysql."
  ]
}, null, 2));

process.exitCode = 1;
`, g.program.App.Name, g.databaseEnvName(), g.generatedMigrationsJSON())
}

func (g *webGenerator) sqliteMigrationRunnerTS() string {
	return fmt.Sprintf(`// Generated by BlackLang. Do not edit manually.

import "dotenv/config";
import { existsSync } from "node:fs";
import Database from "better-sqlite3";

const appName = %q;
const targetDatabase = "sqlite";
const databaseEnvName = %q;
const databaseWasConfigured = Boolean(process.env[databaseEnvName]);
process.env[databaseEnvName] = process.env[databaseEnvName] ?? %q;
const databaseUrl = process.env[databaseEnvName] ?? %q;
const filePath = databaseUrl.startsWith("file:") ? databaseUrl.slice(5) : databaseUrl;

%stype MigrationCheck = {
  kind: string;
  target: string;
  status: string;
  reason: string;
  sourceTable?: string;
  sourceExists?: boolean;
  targetExists?: boolean;
  tableExists?: boolean;
};

type MigrationStatus = {
  name: string;
  file: string;
  operations: number;
  applied: boolean;
  pending: boolean;
  safeToApply: boolean;
  checks: MigrationCheck[];
};

type MigrationSummary = {
  total: number;
  applied: number;
  pending: number;
  unsafe: number;
};

type MigrationCommandResult = {
  success: boolean;
  command: string;
  mode: "plan" | "apply";
  app: string;
  targetDatabase: string;
  databaseEnv: string;
  databaseConfigured: boolean;
  databaseReachable: boolean;
  ready: boolean;
  summary: MigrationSummary;
  migrations: MigrationStatus[];
  applied: string[];
  skipped: string[];
  errors: string[];
  steps: string[];
};

function quoteIdentifier(value: string): string {
  return "\"" + value.replace(/"/g, "\"\"") + "\"";
}

function redactError(error: unknown): string {
  let message = error instanceof Error ? error.message : String(error);
  for (const sensitive of [databaseUrl, filePath]) {
    if (sensitive) {
      message = message.split(sensitive).join("<redacted>");
    }
  }
  return message;
}

function sqliteTableExists(db: Database.Database, name: string): boolean {
  const row = db.prepare("SELECT name FROM sqlite_master WHERE type = 'table' AND name = ?").get(name) as { name: string } | undefined;
  return Boolean(row);
}

function sqliteColumnExists(db: Database.Database, table: string, column: string): boolean {
  const rows = db.prepare("PRAGMA table_info(" + quoteIdentifier(table) + ")").all() as Array<{ name: string }>;
  return rows.some((row) => row.name === column);
}

function ensureBlackMigrationTable(db: Database.Database): void {
  db.exec("CREATE TABLE IF NOT EXISTS \"BlackMigration\" (\"id\" TEXT NOT NULL PRIMARY KEY, \"appliedAt\" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);");
}

function sqliteMigrationApplied(db: Database.Database, name: string): boolean {
  if (!sqliteTableExists(db, "BlackMigration")) {
    return false;
  }
  const row = db.prepare("SELECT id FROM \"BlackMigration\" WHERE id = ?").get(name) as { id: string } | undefined;
  return Boolean(row);
}

function markSQLiteMigrationApplied(db: Database.Database, name: string): void {
  db.prepare("INSERT OR IGNORE INTO \"BlackMigration\" (id) VALUES (?)").run(name);
}

function operationTarget(operation: BlackMigrationOperation): string {
  if (operation.kind === "entity") {
    return operation.from + " -> " + operation.to;
  }
  return String(operation.entity ?? "") + "." + String(operation.oldColumn ?? operation.from) + " -> " + String(operation.newColumn ?? operation.to);
}

function sqliteOperationCheck(db: Database.Database, migration: BlackMigration, operation: BlackMigrationOperation): MigrationCheck {
  if (operation.kind === "entity") {
    const sourceExists = sqliteTableExists(db, operation.from);
    const targetExists = sqliteTableExists(db, operation.to);
    if (sourceExists && targetExists) {
      return {
        kind: operation.kind,
        target: operationTarget(operation),
        status: "conflict",
        reason: "Both source and target tables exist; applying the rename could hide data intent.",
        sourceExists,
        targetExists
      };
    }
    if (sourceExists) {
      return {
        kind: operation.kind,
        target: operationTarget(operation),
        status: "ready",
        reason: "Source table exists and target table does not.",
        sourceExists,
        targetExists
      };
    }
    if (targetExists) {
      return {
        kind: operation.kind,
        target: operationTarget(operation),
        status: "already-renamed",
        reason: "Target table already exists; apply mode will record the migration if it is not in the ledger.",
        sourceExists,
        targetExists
      };
    }
    return {
      kind: operation.kind,
      target: operationTarget(operation),
      status: "noop-or-fresh-database",
      reason: "Neither table exists; this is safe for a fresh generated setup path.",
      sourceExists,
      targetExists
    };
  }

  const declaredTable = operation.entity ?? "";
  let table = declaredTable;
  let sourceTable = "";
  let tableExists = declaredTable !== "" && sqliteTableExists(db, declaredTable);
  if (!tableExists) {
    for (const candidate of migration.operations) {
      if (candidate.kind === "entity" && candidate.to === declaredTable && sqliteTableExists(db, candidate.from) && !sqliteTableExists(db, candidate.to)) {
        table = candidate.from;
        sourceTable = candidate.from;
        tableExists = true;
        break;
      }
    }
  }
  if (!tableExists) {
    return {
      kind: operation.kind,
      target: operationTarget(operation),
      status: "table-missing",
      reason: "The owning table and same-migration rename source are not present yet; apply mode will leave the rename as a fresh setup no-op.",
      tableExists
    };
  }
  const oldColumn = operation.oldColumn ?? operation.from;
  const newColumn = operation.newColumn ?? operation.to;
  const sourceExists = sqliteColumnExists(db, table, oldColumn);
  const targetExists = sqliteColumnExists(db, table, newColumn);
  if (sourceExists && targetExists) {
    return {
      kind: operation.kind,
      target: operationTarget(operation),
      status: "conflict",
      reason: "Both source and target columns exist; applying the rename could hide data intent.",
      sourceTable: sourceTable || undefined,
      sourceExists,
      targetExists,
      tableExists
    };
  }
  if (sourceExists) {
    return {
      kind: operation.kind,
      target: operationTarget(operation),
      status: "ready",
      reason: sourceTable ? "Source column exists on the table that will be renamed first." : "Source column exists and target column does not.",
      sourceTable: sourceTable || undefined,
      sourceExists,
      targetExists,
      tableExists
    };
  }
  if (targetExists) {
    return {
      kind: operation.kind,
      target: operationTarget(operation),
      status: "already-renamed",
      reason: sourceTable ? "Target column already exists on the table that will be renamed first; apply mode will record the migration if it is not in the ledger." : "Target column already exists; apply mode will record the migration if it is not in the ledger.",
      sourceTable: sourceTable || undefined,
      sourceExists,
      targetExists,
      tableExists
    };
  }
  return {
    kind: operation.kind,
    target: operationTarget(operation),
    status: "missing-column",
    reason: "The table exists, but neither source nor target column exists.",
    sourceTable: sourceTable || undefined,
    sourceExists,
    targetExists,
    tableExists
  };
}

function isUnsafeCheck(check: MigrationCheck): boolean {
  return check.status === "conflict" || check.status === "missing-column" || check.status === "database-missing";
}

function summarizeMigrations(migrations: MigrationStatus[]): MigrationSummary {
  return {
    total: migrations.length,
    applied: migrations.filter((migration) => migration.applied).length,
    pending: migrations.filter((migration) => migration.pending).length,
    unsafe: migrations.filter((migration) => migration.pending && !migration.safeToApply).length
  };
}

function migrationSteps(mode: "plan" | "apply"): string[] {
  if (mode === "apply") {
    return [
      "Run npm run db:migrate:plan first in the same environment.",
      "Apply mode runs only declared rename migrations and records them in BlackMigration.",
      "Run npm run db:setup after apply mode so the normal generated setup and seed path runs."
    ];
  }
  return [
    "Review every pending migration and unsafe check before apply mode.",
    "Run npm run db:migrate only after the plan is ready.",
    "Run npm run db:setup after apply mode so the normal generated setup and seed path runs."
  ];
}

function buildDatabaseMissingPlan(): MigrationCommandResult {
  const migrations = blackMigrations.map((migration): MigrationStatus => ({
    name: migration.name,
    file: migration.file,
    operations: migration.operations.length,
    applied: false,
    pending: true,
    safeToApply: false,
    checks: [{
      kind: "database",
      target: "database",
      status: "database-missing",
      reason: "SQLite database file does not exist; plan mode did not create it."
    }]
  }));
  return {
    success: true,
    command: "db:migrate:plan",
    mode: "plan",
    app: appName,
    targetDatabase,
    databaseEnv: databaseEnvName,
    databaseConfigured: databaseWasConfigured,
    databaseReachable: false,
    ready: false,
    summary: summarizeMigrations(migrations),
    migrations,
    applied: [],
    skipped: [],
    errors: [],
    steps: migrationSteps("plan")
  };
}

function buildSQLitePlan(): MigrationCommandResult {
  if (!existsSync(filePath)) {
    return buildDatabaseMissingPlan();
  }
  const db = new Database(filePath, { readonly: true, fileMustExist: true });
  try {
    const migrations = blackMigrations.map((migration): MigrationStatus => {
      const applied = sqliteMigrationApplied(db, migration.name);
      const checks = applied
        ? [{
            kind: "ledger",
            target: migration.name,
            status: "applied",
            reason: "The migration is already present in BlackMigration."
          }]
        : migration.operations.map((operation) => sqliteOperationCheck(db, migration, operation));
      return {
        name: migration.name,
        file: migration.file,
        operations: migration.operations.length,
        applied,
        pending: !applied,
        safeToApply: !checks.some(isUnsafeCheck),
        checks
      };
    });
    const summary = summarizeMigrations(migrations);
    return {
      success: true,
      command: "db:migrate:plan",
      mode: "plan",
      app: appName,
      targetDatabase,
      databaseEnv: databaseEnvName,
      databaseConfigured: databaseWasConfigured,
      databaseReachable: true,
      ready: summary.unsafe === 0,
      summary,
      migrations,
      applied: [],
      skipped: [],
      errors: [],
      steps: migrationSteps("plan")
    };
  } finally {
    db.close();
  }
}

function applySQLiteEntityRename(db: Database.Database, migration: BlackMigration, operation: BlackMigrationOperation): void {
  const sourceExists = sqliteTableExists(db, operation.from);
  const targetExists = sqliteTableExists(db, operation.to);
  if (sourceExists && targetExists) {
    throw new Error("Migration " + migration.name + " cannot rename table " + operation.from + " to " + operation.to + " because both tables exist.");
  }
  if (sourceExists) {
    db.exec("ALTER TABLE " + quoteIdentifier(operation.from) + " RENAME TO " + quoteIdentifier(operation.to));
  }
}

function applySQLiteFieldRename(db: Database.Database, migration: BlackMigration, operation: BlackMigrationOperation): void {
  if (!operation.entity || !operation.oldColumn || !operation.newColumn) {
    throw new Error("Migration " + migration.name + " has an incomplete field rename operation.");
  }
  if (!sqliteTableExists(db, operation.entity)) {
    return;
  }
  const sourceExists = sqliteColumnExists(db, operation.entity, operation.oldColumn);
  const targetExists = sqliteColumnExists(db, operation.entity, operation.newColumn);
  if (sourceExists && targetExists) {
    throw new Error("Migration " + migration.name + " cannot rename column " + operation.entity + "." + operation.oldColumn + " to " + operation.newColumn + " because both columns exist.");
  }
  if (sourceExists) {
    db.exec("ALTER TABLE " + quoteIdentifier(operation.entity) + " RENAME COLUMN " + quoteIdentifier(operation.oldColumn) + " TO " + quoteIdentifier(operation.newColumn));
    return;
  }
  if (!targetExists) {
    throw new Error("Migration " + migration.name + " cannot find column " + operation.entity + "." + operation.oldColumn + " or " + operation.entity + "." + operation.newColumn + ".");
  }
}

function applySQLiteMigrations(): { applied: string[]; skipped: string[] } {
  const applied: string[] = [];
  const skipped: string[] = [];
  const db = new Database(filePath);
  try {
    ensureBlackMigrationTable(db);
    const transaction = db.transaction((migration: BlackMigration) => {
      if (sqliteMigrationApplied(db, migration.name)) {
        skipped.push(migration.name);
        return;
      }
      for (const operation of migration.operations) {
        if (operation.kind === "entity") {
          applySQLiteEntityRename(db, migration, operation);
        } else {
          applySQLiteFieldRename(db, migration, operation);
        }
      }
      markSQLiteMigrationApplied(db, migration.name);
      applied.push(migration.name);
    });

    for (const migration of blackMigrations) {
      transaction(migration);
    }
  } finally {
    db.close();
  }
  return { applied, skipped };
}

function printResult(result: MigrationCommandResult): void {
  console.log(JSON.stringify(result, null, 2));
}

function run(): void {
  const mode: "plan" | "apply" = process.argv.includes("--apply") ? "apply" : "plan";
  try {
    if (mode === "plan") {
      printResult(buildSQLitePlan());
      return;
    }
    const applyResult = applySQLiteMigrations();
    const plan = buildSQLitePlan();
    printResult({
      ...plan,
      success: true,
      command: "db:migrate",
      mode: "apply",
      ready: true,
      applied: applyResult.applied,
      skipped: applyResult.skipped,
      steps: migrationSteps("apply")
    });
  } catch (error) {
    printResult({
      success: false,
      command: mode === "apply" ? "db:migrate" : "db:migrate:plan",
      mode,
      app: appName,
      targetDatabase,
      databaseEnv: databaseEnvName,
      databaseConfigured: databaseWasConfigured,
      databaseReachable: false,
      ready: false,
      summary: { total: blackMigrations.length, applied: 0, pending: blackMigrations.length, unsafe: blackMigrations.length },
      migrations: [],
      applied: [],
      skipped: [],
      errors: [redactError(error)],
      steps: migrationSteps(mode)
    });
    process.exit(1);
  }
}

run();
`, g.program.App.Name, g.databaseEnvName(), g.defaultDatabaseURL(), g.defaultDatabaseURL(), g.migrationRuntimeDataTS())
}

func (g *webGenerator) postgresMigrationRunnerTS() string {
	return fmt.Sprintf(`// Generated by BlackLang. Do not edit manually.

import "dotenv/config";
import pg from "pg";

const { Client } = pg;
type PgClient = InstanceType<typeof Client>;

const appName = %q;
const targetDatabase = "postgresql";
const databaseEnvName = %q;
const databaseWasConfigured = Boolean(process.env[databaseEnvName]);
process.env[databaseEnvName] = process.env[databaseEnvName] ?? %q;
const databaseUrl = process.env[databaseEnvName] ?? %q;

%stype MigrationCheck = {
  kind: string;
  target: string;
  status: string;
  reason: string;
  sourceTable?: string;
  sourceExists?: boolean;
  targetExists?: boolean;
  tableExists?: boolean;
};

type MigrationStatus = {
  name: string;
  file: string;
  operations: number;
  applied: boolean;
  pending: boolean;
  safeToApply: boolean;
  checks: MigrationCheck[];
};

type MigrationSummary = {
  total: number;
  applied: number;
  pending: number;
  unsafe: number;
};

type MigrationCommandResult = {
  success: boolean;
  command: string;
  mode: "plan" | "apply";
  app: string;
  targetDatabase: string;
  databaseEnv: string;
  databaseConfigured: boolean;
  databaseReachable: boolean;
  ready: boolean;
  summary: MigrationSummary;
  migrations: MigrationStatus[];
  applied: string[];
  skipped: string[];
  errors: string[];
  steps: string[];
};

function quoteIdentifier(value: string): string {
  return "\"" + value.replace(/"/g, "\"\"") + "\"";
}

function redactError(error: unknown): string {
  let message = error instanceof Error ? error.message : String(error);
  if (databaseUrl) {
    message = message.split(databaseUrl).join("<redacted>");
  }
  return message;
}

async function ensureBlackMigrationTable(client: PgClient): Promise<void> {
  await client.query("CREATE TABLE IF NOT EXISTS \"BlackMigration\" (\"id\" TEXT NOT NULL PRIMARY KEY, \"appliedAt\" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)");
}

async function postgresMigrationApplied(client: PgClient, name: string): Promise<boolean> {
  const tableExists = await postgresTableExists(client, "BlackMigration");
  if (!tableExists) {
    return false;
  }
  const result = await client.query<{ id: string }>("SELECT \"id\" FROM \"BlackMigration\" WHERE \"id\" = $1", [name]);
  return result.rows.length > 0;
}

async function markPostgresMigrationApplied(client: PgClient, name: string): Promise<void> {
  await client.query("INSERT INTO \"BlackMigration\" (\"id\") VALUES ($1) ON CONFLICT (\"id\") DO NOTHING", [name]);
}

async function postgresTableExists(client: PgClient, name: string): Promise<boolean> {
  const result = await client.query<{ exists: boolean }>(
    "SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = current_schema() AND table_name = $1) AS exists",
    [name]
  );
  return Boolean(result.rows[0]?.exists);
}

async function postgresColumnExists(client: PgClient, table: string, column: string): Promise<boolean> {
  const result = await client.query<{ exists: boolean }>(
    "SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = $1 AND column_name = $2) AS exists",
    [table, column]
  );
  return Boolean(result.rows[0]?.exists);
}

function operationTarget(operation: BlackMigrationOperation): string {
  if (operation.kind === "entity") {
    return operation.from + " -> " + operation.to;
  }
  return String(operation.entity ?? "") + "." + String(operation.oldColumn ?? operation.from) + " -> " + String(operation.newColumn ?? operation.to);
}

async function postgresOperationCheck(client: PgClient, migration: BlackMigration, operation: BlackMigrationOperation): Promise<MigrationCheck> {
  if (operation.kind === "entity") {
    const sourceExists = await postgresTableExists(client, operation.from);
    const targetExists = await postgresTableExists(client, operation.to);
    if (sourceExists && targetExists) {
      return {
        kind: operation.kind,
        target: operationTarget(operation),
        status: "conflict",
        reason: "Both source and target tables exist; applying the rename could hide data intent.",
        sourceExists,
        targetExists
      };
    }
    if (sourceExists) {
      return {
        kind: operation.kind,
        target: operationTarget(operation),
        status: "ready",
        reason: "Source table exists and target table does not.",
        sourceExists,
        targetExists
      };
    }
    if (targetExists) {
      return {
        kind: operation.kind,
        target: operationTarget(operation),
        status: "already-renamed",
        reason: "Target table already exists; apply mode will record the migration if it is not in the ledger.",
        sourceExists,
        targetExists
      };
    }
    return {
      kind: operation.kind,
      target: operationTarget(operation),
      status: "noop-or-fresh-database",
      reason: "Neither table exists; this is safe for a fresh generated setup path.",
      sourceExists,
      targetExists
    };
  }

  const declaredTable = operation.entity ?? "";
  let table = declaredTable;
  let sourceTable = "";
  let tableExists = declaredTable !== "" && await postgresTableExists(client, declaredTable);
  if (!tableExists) {
    for (const candidate of migration.operations) {
      if (candidate.kind === "entity" && candidate.to === declaredTable && await postgresTableExists(client, candidate.from) && !(await postgresTableExists(client, candidate.to))) {
        table = candidate.from;
        sourceTable = candidate.from;
        tableExists = true;
        break;
      }
    }
  }
  if (!tableExists) {
    return {
      kind: operation.kind,
      target: operationTarget(operation),
      status: "table-missing",
      reason: "The owning table and same-migration rename source are not present yet; apply mode will leave the rename as a fresh setup no-op.",
      tableExists
    };
  }
  const oldColumn = operation.oldColumn ?? operation.from;
  const newColumn = operation.newColumn ?? operation.to;
  const sourceExists = await postgresColumnExists(client, table, oldColumn);
  const targetExists = await postgresColumnExists(client, table, newColumn);
  if (sourceExists && targetExists) {
    return {
      kind: operation.kind,
      target: operationTarget(operation),
      status: "conflict",
      reason: "Both source and target columns exist; applying the rename could hide data intent.",
      sourceTable: sourceTable || undefined,
      sourceExists,
      targetExists,
      tableExists
    };
  }
  if (sourceExists) {
    return {
      kind: operation.kind,
      target: operationTarget(operation),
      status: "ready",
      reason: sourceTable ? "Source column exists on the table that will be renamed first." : "Source column exists and target column does not.",
      sourceTable: sourceTable || undefined,
      sourceExists,
      targetExists,
      tableExists
    };
  }
  if (targetExists) {
    return {
      kind: operation.kind,
      target: operationTarget(operation),
      status: "already-renamed",
      reason: sourceTable ? "Target column already exists on the table that will be renamed first; apply mode will record the migration if it is not in the ledger." : "Target column already exists; apply mode will record the migration if it is not in the ledger.",
      sourceTable: sourceTable || undefined,
      sourceExists,
      targetExists,
      tableExists
    };
  }
  return {
    kind: operation.kind,
    target: operationTarget(operation),
    status: "missing-column",
    reason: "The table exists, but neither source nor target column exists.",
    sourceTable: sourceTable || undefined,
    sourceExists,
    targetExists,
    tableExists
  };
}

function isUnsafeCheck(check: MigrationCheck): boolean {
  return check.status === "conflict" || check.status === "missing-column" || check.status === "database-missing";
}

function summarizeMigrations(migrations: MigrationStatus[]): MigrationSummary {
  return {
    total: migrations.length,
    applied: migrations.filter((migration) => migration.applied).length,
    pending: migrations.filter((migration) => migration.pending).length,
    unsafe: migrations.filter((migration) => migration.pending && !migration.safeToApply).length
  };
}

function migrationSteps(mode: "plan" | "apply"): string[] {
  if (mode === "apply") {
    return [
      "Run npm run db:migrate:plan first in the same environment.",
      "Apply mode runs only declared rename migrations and records them in BlackMigration.",
      "Run npm run db:setup after apply mode so the normal generated setup and seed path runs."
    ];
  }
  return [
    "Review every pending migration and unsafe check before apply mode.",
    "Run npm run db:migrate only after the plan is ready.",
    "Run npm run db:setup after apply mode so the normal generated setup and seed path runs."
  ];
}

function buildUnreachablePlan(error: unknown): MigrationCommandResult {
  const migrations = blackMigrations.map((migration): MigrationStatus => ({
    name: migration.name,
    file: migration.file,
    operations: migration.operations.length,
    applied: false,
    pending: true,
    safeToApply: false,
    checks: [{
      kind: "database",
      target: "database",
      status: "database-unreachable",
      reason: "PostgreSQL database could not be reached in read-only plan mode."
    }]
  }));
  return {
    success: true,
    command: "db:migrate:plan",
    mode: "plan",
    app: appName,
    targetDatabase,
    databaseEnv: databaseEnvName,
    databaseConfigured: databaseWasConfigured,
    databaseReachable: false,
    ready: false,
    summary: summarizeMigrations(migrations),
    migrations,
    applied: [],
    skipped: [],
    errors: [redactError(error)],
    steps: migrationSteps("plan")
  };
}

async function buildPostgresPlan(): Promise<MigrationCommandResult> {
  const client = new Client({ connectionString: databaseUrl });
  try {
    await client.connect();
  } catch (error) {
    return buildUnreachablePlan(error);
  }
  try {
    const migrations: MigrationStatus[] = [];
    for (const migration of blackMigrations) {
      const applied = await postgresMigrationApplied(client, migration.name);
      const checks = applied
        ? [{
            kind: "ledger",
            target: migration.name,
            status: "applied",
            reason: "The migration is already present in BlackMigration."
          }]
        : [];
      if (!applied) {
        for (const operation of migration.operations) {
          checks.push(await postgresOperationCheck(client, migration, operation));
        }
      }
      migrations.push({
        name: migration.name,
        file: migration.file,
        operations: migration.operations.length,
        applied,
        pending: !applied,
        safeToApply: !checks.some(isUnsafeCheck),
        checks
      });
    }
    const summary = summarizeMigrations(migrations);
    return {
      success: true,
      command: "db:migrate:plan",
      mode: "plan",
      app: appName,
      targetDatabase,
      databaseEnv: databaseEnvName,
      databaseConfigured: databaseWasConfigured,
      databaseReachable: true,
      ready: summary.unsafe === 0,
      summary,
      migrations,
      applied: [],
      skipped: [],
      errors: [],
      steps: migrationSteps("plan")
    };
  } finally {
    await client.end();
  }
}

async function applyPostgresEntityRename(client: PgClient, migration: BlackMigration, operation: BlackMigrationOperation): Promise<void> {
  const sourceExists = await postgresTableExists(client, operation.from);
  const targetExists = await postgresTableExists(client, operation.to);
  if (sourceExists && targetExists) {
    throw new Error("Migration " + migration.name + " cannot rename table " + operation.from + " to " + operation.to + " because both tables exist.");
  }
  if (sourceExists) {
    await client.query("ALTER TABLE " + quoteIdentifier(operation.from) + " RENAME TO " + quoteIdentifier(operation.to));
  }
}

async function applyPostgresFieldRename(client: PgClient, migration: BlackMigration, operation: BlackMigrationOperation): Promise<void> {
  if (!operation.entity || !operation.oldColumn || !operation.newColumn) {
    throw new Error("Migration " + migration.name + " has an incomplete field rename operation.");
  }
  if (!(await postgresTableExists(client, operation.entity))) {
    return;
  }
  const sourceExists = await postgresColumnExists(client, operation.entity, operation.oldColumn);
  const targetExists = await postgresColumnExists(client, operation.entity, operation.newColumn);
  if (sourceExists && targetExists) {
    throw new Error("Migration " + migration.name + " cannot rename column " + operation.entity + "." + operation.oldColumn + " to " + operation.newColumn + " because both columns exist.");
  }
  if (sourceExists) {
    await client.query("ALTER TABLE " + quoteIdentifier(operation.entity) + " RENAME COLUMN " + quoteIdentifier(operation.oldColumn) + " TO " + quoteIdentifier(operation.newColumn));
    return;
  }
  if (!targetExists) {
    throw new Error("Migration " + migration.name + " cannot find column " + operation.entity + "." + operation.oldColumn + " or " + operation.entity + "." + operation.newColumn + ".");
  }
}

async function applyPostgresMigrations(): Promise<{ applied: string[]; skipped: string[] }> {
  const applied: string[] = [];
  const skipped: string[] = [];
  const client = new Client({ connectionString: databaseUrl });
  await client.connect();
  try {
    await ensureBlackMigrationTable(client);
    for (const migration of blackMigrations) {
      if (await postgresMigrationApplied(client, migration.name)) {
        skipped.push(migration.name);
        continue;
      }
      await client.query("BEGIN");
      try {
        for (const operation of migration.operations) {
          if (operation.kind === "entity") {
            await applyPostgresEntityRename(client, migration, operation);
          } else {
            await applyPostgresFieldRename(client, migration, operation);
          }
        }
        await markPostgresMigrationApplied(client, migration.name);
        await client.query("COMMIT");
        applied.push(migration.name);
      } catch (error) {
        await client.query("ROLLBACK");
        throw error;
      }
    }
  } finally {
    await client.end();
  }
  return { applied, skipped };
}

function printResult(result: MigrationCommandResult): void {
  console.log(JSON.stringify(result, null, 2));
}

async function run(): Promise<void> {
  const mode: "plan" | "apply" = process.argv.includes("--apply") ? "apply" : "plan";
  try {
    if (mode === "plan") {
      printResult(await buildPostgresPlan());
      return;
    }
    const applyResult = await applyPostgresMigrations();
    const plan = await buildPostgresPlan();
    printResult({
      ...plan,
      success: true,
      command: "db:migrate",
      mode: "apply",
      ready: true,
      applied: applyResult.applied,
      skipped: applyResult.skipped,
      steps: migrationSteps("apply")
    });
  } catch (error) {
    printResult({
      success: false,
      command: mode === "apply" ? "db:migrate" : "db:migrate:plan",
      mode,
      app: appName,
      targetDatabase,
      databaseEnv: databaseEnvName,
      databaseConfigured: databaseWasConfigured,
      databaseReachable: false,
      ready: false,
      summary: { total: blackMigrations.length, applied: 0, pending: blackMigrations.length, unsafe: blackMigrations.length },
      migrations: [],
      applied: [],
      skipped: [],
      errors: [redactError(error)],
      steps: migrationSteps(mode)
    });
    process.exit(1);
  }
}

void run();
`, g.program.App.Name, g.databaseEnvName(), g.defaultDatabaseURL(), g.defaultDatabaseURL(), g.migrationRuntimeDataTS())
}
