package main

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

type generatedBrowserExpectation struct {
	Kind  string `json:"kind"`
	Value string `json:"value"`
}

type generatedBrowserCheck struct {
	Name         string                        `json:"name"`
	Page         string                        `json:"page"`
	Expectations []generatedBrowserExpectation `json:"expectations"`
}

func (g *webGenerator) hasBrowserChecks() bool {
	return len(g.program.Tests) > 0
}

func (g *webGenerator) browserCheckTestTSX() string {
	return fmt.Sprintf(`// Generated by BlackLang. Do not edit manually.

import assert from "node:assert/strict";
import { renderToString } from "react-dom/server";
import { App } from "./App";

type BrowserExpectation = { kind: "text" | "page" | "action"; value: string };
type BrowserCheck = { name: string; page: string; expectations: BrowserExpectation[] };

const declaredPages: string[] = %s;
const declaredActionsByPage: Record<string, string[]> = %s;
const generatedTextCatalog: string[] = %s;
const checks: BrowserCheck[] = %s;

const html = renderToString(<App />);
assert.ok(html.length > 0, "App should render non-empty HTML for browser checks");

function hasGeneratedText(value: string): boolean {
  return html.includes(value) || generatedTextCatalog.includes(value);
}

for (const check of checks) {
  assert.ok(declaredPages.includes(check.page), "Browser check " + check.name + " should target generated page " + check.page);
  for (const expectation of check.expectations) {
    if (expectation.kind === "text") {
      assert.ok(hasGeneratedText(expectation.value), "Browser check " + check.name + " expected generated text " + expectation.value);
    }
    if (expectation.kind === "page") {
      assert.ok(declaredPages.includes(expectation.value), "Browser check " + check.name + " expected generated page " + expectation.value);
    }
    if (expectation.kind === "action") {
      assert.ok((declaredActionsByPage[check.page] ?? []).includes(expectation.value), "Browser check " + check.name + " expected action " + expectation.value + " on page " + check.page);
    }
  }
}

console.log("BlackLang generated browser checks passed");
`, browserJSONStringArray(g.browserCheckPageNames()), browserJSONMap(g.browserCheckActionsByPage()), browserJSONStringArray(g.browserCheckTextCatalog()), browserJSONChecks(g.program.Tests))
}

func (g *webGenerator) browserCheckPageNames() []string {
	pages := []string{}
	for _, page := range g.program.Pages {
		pages = append(pages, page.Name)
	}
	return pages
}

func (g *webGenerator) browserCheckActionsByPage() map[string][]string {
	actionsByPage := map[string][]string{}
	for _, page := range g.program.Pages {
		actions := append([]string{}, page.Actions...)
		sort.Strings(actions)
		actionsByPage[page.Name] = actions
	}
	return actionsByPage
}

func (g *webGenerator) browserCheckTextCatalog() []string {
	values := []string{}
	add := func(value string) {
		value = strings.TrimSpace(value)
		if value == "" || containsString(values, value) {
			return
		}
		values = append(values, value)
	}
	add(g.program.App.Name)
	add(g.uiLabelFallback("app.title", g.program.App.Name))
	add(g.uiLabelFallback("app.checkingSession", "Checking session..."))
	add("Checking session...")
	add("Sign in")
	add("Create account")
	add("Login")
	add("Register")
	add("Email")
	add("Password")
	for _, page := range g.program.Pages {
		add(page.Name)
		add(g.uiLabelFallback("page."+page.Name, page.Name))
	}
	if g.program.Auth != nil {
		add("Users")
		add("Audit")
		add(g.uiLabelFallback("page.Users", "Users"))
		add(g.uiLabelFallback("page.Audit", "Audit"))
	}
	for _, page := range g.program.Pages {
		if entity, ok := g.findEntity(page.Source); ok {
			for _, field := range entity.Fields {
				add(g.fieldLabel(entity, field))
			}
			for _, field := range entity.ComputedFields {
				add(g.computedFieldLabel(entity, field))
			}
			for _, action := range page.Actions {
				add(action)
				switch action {
				case "create":
					add(g.uiLabelFallback("action.create", "Create"))
					add(g.uiLabelFallback("action.new."+entity.Name, "New "+entity.Name))
					add(g.uiLabelFallback("action.create."+entity.Name, "Create "+entity.Name))
				case "edit":
					add(g.uiLabelFallback("action.edit", "Edit"))
					add(g.uiLabelFallback("action.edit."+entity.Name, "Edit "+entity.Name))
				case "delete":
					add(g.uiLabelFallback("action.delete", "Delete"))
					add(g.uiLabelFallback("action.deleteSelected", "Delete Selected"))
				case "archive":
					add(g.uiLabelFallback("action.archive", "Archive"))
				case "restore":
					add(g.uiLabelFallback("action.restore", "Restore"))
				default:
					add(g.uiLabelFallback("action."+action, identifierLabel(action)))
				}
			}
		}
	}
	for _, label := range g.program.Labels {
		for _, translation := range label.Translations {
			add(translation.Text)
		}
	}
	sort.Strings(values)
	return values
}

func browserJSONChecks(tests []TestDecl) string {
	checks := []generatedBrowserCheck{}
	for _, test := range tests {
		check := generatedBrowserCheck{
			Name:         test.Name,
			Page:         test.Page,
			Expectations: []generatedBrowserExpectation{},
		}
		for _, expectation := range test.Expectations {
			check.Expectations = append(check.Expectations, generatedBrowserExpectation{Kind: expectation.Kind, Value: expectation.Value})
		}
		checks = append(checks, check)
	}
	content, err := json.MarshalIndent(checks, "", "  ")
	if err != nil {
		return "[]"
	}
	return string(content)
}

func browserJSONStringArray(values []string) string {
	content, err := json.MarshalIndent(values, "", "  ")
	if err != nil {
		return "[]"
	}
	return string(content)
}

func browserJSONMap(values map[string][]string) string {
	content, err := json.MarshalIndent(values, "", "  ")
	if err != nil {
		return "{}"
	}
	return string(content)
}
