package main

import (
	"fmt"
	"strings"
)

func (g *webGenerator) apiSmokeTestTS() string {
	var builder strings.Builder
	builder.WriteString("// Generated by BlackLang. Do not edit manually.\n\n")
	builder.WriteString("import assert from \"node:assert/strict\";\n")
	builder.WriteString("import http from \"node:http\";\n")
	builder.WriteString("import type { AddressInfo } from \"node:net\";\n\n")
	if g.targetDatabase() == "sqlite" {
		builder.WriteString(fmt.Sprintf("process.env.%s = \"file::memory:\";\n", g.databaseEnvName()))
		if g.databaseEnvName() != "DATABASE_URL" {
			builder.WriteString("process.env.DATABASE_URL = \"file::memory:\";\n")
		}
	}
	if cors := g.corsConfig(); cors != nil && cors.Origins.Name != "" {
		builder.WriteString("process.env." + cors.Origins.Name + " = \"https://allowed.example\";\n")
	}
	builder.WriteString("\n")
	builder.WriteString("const { createApp } = await import(\"./server\");\n")
	builder.WriteString("const server = http.createServer(createApp());\n\n")
	if g.hasOpsObserve() {
		builder.WriteString("let observeRequests = 0;\n")
		builder.WriteString("const observeEvents: Array<Record<string, unknown>> = [];\n")
		builder.WriteString("const observeServer = http.createServer((req, res) => {\n")
		builder.WriteString("  let body = \"\";\n")
		builder.WriteString("  req.setEncoding(\"utf8\");\n")
		builder.WriteString("  req.on(\"data\", (chunk: string) => { body += chunk; });\n")
		builder.WriteString("  req.on(\"end\", () => {\n")
		builder.WriteString("    observeRequests += 1;\n")
		builder.WriteString("    try {\n")
		builder.WriteString("      observeEvents.push(JSON.parse(body) as Record<string, unknown>);\n")
		builder.WriteString("    } catch (_error) {\n")
		builder.WriteString("      observeEvents.push({ invalid: true });\n")
		builder.WriteString("    }\n")
		builder.WriteString("    res.statusCode = 204;\n")
		builder.WriteString("    res.end();\n")
		builder.WriteString("  });\n")
		builder.WriteString("});\n\n")
	}
	builder.WriteString("function listenServer(target: ReturnType<typeof http.createServer>) {\n")
	builder.WriteString("  return new Promise<void>((resolve, reject) => {\n")
	builder.WriteString("    const onError = (error: Error) => reject(error);\n")
	builder.WriteString("    target.once(\"error\", onError);\n")
	builder.WriteString("    target.listen(0, \"127.0.0.1\", () => {\n")
	builder.WriteString("      target.off(\"error\", onError);\n")
	builder.WriteString("      resolve();\n")
	builder.WriteString("    });\n")
	builder.WriteString("  });\n")
	builder.WriteString("}\n\n")
	builder.WriteString("function closeServer(target: ReturnType<typeof http.createServer>) {\n")
	builder.WriteString("  return new Promise<void>((resolve, reject) => {\n")
	builder.WriteString("    target.close((error) => error ? reject(error) : resolve());\n")
	builder.WriteString("  });\n")
	builder.WriteString("}\n\n")
	if g.hasOpsObserve() {
		builder.WriteString("await listenServer(observeServer);\n")
		builder.WriteString("const observeAddress = observeServer.address() as AddressInfo;\n")
		builder.WriteString(fmt.Sprintf("process.env[%s] = `http://127.0.0.1:${observeAddress.port}/events`;\n", contractJSONString(g.opsObserveEndpointEnv())))
	}
	builder.WriteString("await listenServer(server);\n")
	builder.WriteString("try {\n")
	builder.WriteString("  const address = server.address() as AddressInfo;\n")
	builder.WriteString("  const baseURL = `http://127.0.0.1:${address.port}`;\n\n")
	builder.WriteString("  const openapi = await fetch(baseURL + \"/openapi.json\");\n")
	builder.WriteString("  assert.equal(openapi.status, 200, \"GET /openapi.json should succeed\");\n")
	if g.hasOpsObserve() {
		builder.WriteString("  assert.match(openapi.headers.get(\"traceparent\") ?? \"\", /^00-[a-f0-9]{32}-[a-f0-9]{16}-[a-f0-9]{2}$/, \"observed responses should include W3C traceparent\");\n")
	}
	builder.WriteString("  const spec = await openapi.json() as { openapi?: string };\n")
	builder.WriteString("  assert.equal(spec.openapi, \"3.1.0\", \"GET /openapi.json should return the generated OpenAPI contract\");\n\n")
	if path := g.opsHealthPath(); path != "" {
		builder.WriteString("  const health = await fetch(baseURL + " + contractJSONString(path) + ");\n")
		builder.WriteString("  assert.equal(health.status, 200, \"ops health endpoint should succeed\");\n")
		builder.WriteString("  const healthBody = await health.json() as { status?: string; app?: string; uptimeSeconds?: number };\n")
		builder.WriteString("  assert.equal(healthBody.status, \"ok\", \"ops health endpoint should report ok\");\n")
		builder.WriteString("  assert.equal(typeof healthBody.uptimeSeconds, \"number\", \"ops health endpoint should include uptimeSeconds\");\n\n")
	}
	if path := g.opsReadinessPath(); path != "" {
		builder.WriteString("  const readiness = await fetch(baseURL + " + contractJSONString(path) + ");\n")
		builder.WriteString("  assert.equal(readiness.status, 200, \"ops readiness endpoint should succeed\");\n")
		builder.WriteString("  const readinessBody = await readiness.json() as { status?: string; database?: string };\n")
		builder.WriteString("  assert.equal(readinessBody.status, \"ready\", \"ops readiness endpoint should report ready\");\n")
		builder.WriteString("  assert.equal(readinessBody.database, \"ok\", \"ops readiness endpoint should check the database\");\n\n")
	}
	if path := g.opsMetricsPath(); path != "" {
		builder.WriteString("  const metrics = await fetch(baseURL + " + contractJSONString(path) + ");\n")
		builder.WriteString("  assert.equal(metrics.status, 200, \"ops metrics endpoint should succeed\");\n")
		builder.WriteString("  const metricsBody = await metrics.json() as { requests?: number; errors?: number; uptimeSeconds?: number; statusCodes?: Record<string, number> };\n")
		builder.WriteString("  assert.equal(typeof metricsBody.requests, \"number\", \"ops metrics endpoint should include request count\");\n")
		builder.WriteString("  assert.equal(typeof metricsBody.errors, \"number\", \"ops metrics endpoint should include error count\");\n")
		builder.WriteString("  assert.equal(typeof metricsBody.uptimeSeconds, \"number\", \"ops metrics endpoint should include uptimeSeconds\");\n\n")
	}
	if g.hasOpsObserve() {
		builder.WriteString("  await new Promise((resolve) => setTimeout(resolve, 100));\n")
		builder.WriteString(fmt.Sprintf("  assert.ok(observeRequests >= 1, \"ops observe %s should receive request events\");\n", g.opsObserveProvider()))
		if g.hasOpsOTLPObserve() {
			builder.WriteString("  assert.ok(observeEvents.some((event) => Array.isArray(event.resourceSpans)), \"ops observe otlp should receive OTLP trace payloads\");\n")
			builder.WriteString("  assert.ok(observeEvents.some((event) => (event.resourceSpans as any[])?.some((resourceSpan: any) => resourceSpan.scopeSpans?.some((scopeSpan: any) => scopeSpan.spans?.some((span: any) => typeof span.traceId === \"string\" && typeof span.spanId === \"string\" && span.kind === 2)))), \"ops observe otlp should include server span trace ids\");\n\n")
		} else {
			builder.WriteString(fmt.Sprintf("  assert.ok(observeEvents.some((event) => event.kind === \"request\" && event.provider === %q && typeof event.traceId === \"string\" && typeof event.spanId === \"string\"), \"ops observe %s should receive structured request events with trace context\");\n\n", g.opsObserveProvider(), g.opsObserveProvider()))
		}
	}
	builder.WriteString(explicitAPISmokeTests(g))
	builder.WriteString(querySummarySmokeTests(g))
	if g.program.Auth != nil {
		builder.WriteString("  const api = await fetch(baseURL + \"/api/__blacklang_missing\");\n")
		builder.WriteString("  assert.equal(api.status, 401, \"authenticated API routes should reject anonymous requests\");\n\n")
	} else {
		builder.WriteString("  const api = await fetch(baseURL + \"/api/__blacklang_missing\");\n")
		builder.WriteString("  assert.equal(api.status, 404, \"unknown API routes should return JSON 404\");\n")
		builder.WriteString("  const apiBody = await api.json() as { error?: string };\n")
		builder.WriteString("  assert.equal(apiBody.error, \"Not found\", \"unknown API routes should return a stable JSON error\");\n\n")
	}
	if cors := g.corsConfig(); cors != nil && cors.Origins.Name != "" {
		builder.WriteString("  const deniedCors = await fetch(baseURL + \"/openapi.json\", { headers: { Origin: \"https://denied.example\" } });\n")
		builder.WriteString("  assert.equal(deniedCors.status, 403, \"CORS should reject origins outside the configured environment list\");\n\n")
		builder.WriteString("  const allowedCors = await fetch(baseURL + \"/openapi.json\", { headers: { Origin: \"https://allowed.example\" } });\n")
		builder.WriteString("  assert.equal(allowedCors.status, 200, \"CORS should allow configured origins\");\n")
		builder.WriteString("  assert.equal(allowedCors.headers.get(\"access-control-allow-origin\"), \"https://allowed.example\");\n\n")
	}
	if g.hasOpsObserve() {
		builder.WriteString("  await new Promise((resolve) => setTimeout(resolve, 100));\n\n")
	}
	builder.WriteString("} finally {\n")
	builder.WriteString("  await closeServer(server);\n")
	if g.hasOpsObserve() {
		builder.WriteString("  await closeServer(observeServer);\n")
	}
	builder.WriteString("}\n\n")
	builder.WriteString("console.log(\"BlackLang generated API smoke tests passed\");\n")
	return builder.String()
}
