package main

import (
	"fmt"
	"strings"
)

func (g *webGenerator) frontendSmokeTestTSX() string {
	var builder strings.Builder
	builder.WriteString("// Generated by BlackLang. Do not edit manually.\n\n")
	builder.WriteString("import assert from \"node:assert/strict\";\n")
	builder.WriteString("import { renderToString } from \"react-dom/server\";\n")
	builder.WriteString("import { App } from \"./App\";\n\n")
	builder.WriteString("const html = renderToString(<App />);\n")
	builder.WriteString("assert.ok(html.length > 0, \"App should render non-empty HTML\");\n")
	if g.program.Auth != nil {
		sessionText := "Checking session"
		if g.hasRuntimeI18N() {
			sessionText = g.uiLabelFallback("app.checkingSession", "Checking session...")
		}
		builder.WriteString(fmt.Sprintf("assert.ok(html.includes(%q), \"authenticated apps should render the session check state before client effects run\");\n", sessionText))
	} else {
		appTitle := g.program.App.Name
		if g.hasRuntimeI18N() {
			appTitle = g.uiLabelFallback("app.title", g.program.App.Name)
		}
		builder.WriteString(fmt.Sprintf("assert.ok(html.includes(%q), \"App shell should render the app name\");\n", appTitle))
		if len(g.program.Pages) > 0 {
			pageTitle := g.program.Pages[0].Name
			if g.hasRuntimeI18N() {
				pageTitle = g.uiLabelFallback("page."+g.program.Pages[0].Name, g.program.Pages[0].Name)
			}
			builder.WriteString(fmt.Sprintf("assert.ok(html.includes(%q), \"App shell should render the first page name\");\n", pageTitle))
		}
	}
	builder.WriteString("console.log(\"BlackLang generated frontend smoke tests passed\");\n")
	return builder.String()
}
