package main

import (
	"encoding/json"
	"fmt"
)

func (g *webGenerator) browserE2ETestTS() string {
	return fmt.Sprintf(`// Generated by BlackLang. Do not edit manually.

import assert from "node:assert/strict";
import { promises as fs, statSync } from "node:fs";
import http from "node:http";
import type { Server } from "node:http";
import net from "node:net";
import type { AddressInfo } from "node:net";
import path from "node:path";
import { chromium } from "playwright-core";
import type { Browser, Locator, Page } from "playwright-core";
import react from "@vitejs/plugin-react";
import { createServer as createViteServer } from "vite";
import type { ViteDevServer } from "vite";

type BrowserExpectation = { kind: "text" | "page" | "action"; value: string };
type BrowserCheck = { name: string; page: string; expectations: BrowserExpectation[] };

const authEnabled = %s;
const seedEnabled = %s;
const databaseProvider = %q;
const databaseEnvName = %q;
const defaultGeneratedDatabaseUrl = %q;
const defaultE2EDatabaseUrl = %q;
const corsOriginsEnvName = %q;
const pageLabels: Record<string, string> = %s;
const actionLabelsByPage: Record<string, Record<string, string>> = %s;
const checks: BrowserCheck[] = %s;

type RuntimeState = {
  apiServer?: Server;
  viteServer?: ViteDevServer;
  browser?: Browser;
};

type AuthDatabaseModule = {
  closeAuthDatabase?: () => void | Promise<void>;
};

type PrismaDatabaseModule = {
  prisma?: {
    $disconnect?: () => Promise<void>;
  };
};

async function main() {
  const state: RuntimeState = {};
  const databaseUrl = selectDatabaseUrl();
  process.env[databaseEnvName] = databaseUrl;
  if (databaseEnvName !== "DATABASE_URL") {
    process.env.DATABASE_URL = databaseUrl;
  }
  const ownsEphemeralSQLite = databaseProvider === "sqlite" && !process.env.BLACKLANG_E2E_DATABASE_URL && databaseUrl === defaultE2EDatabaseUrl;

  if (ownsEphemeralSQLite) {
    await removeSQLiteDatabaseFiles(databaseUrl);
  }

  try {
    await import("./setup-db");
    if (seedEnabled) {
      await import("./seed");
    }

    const apiPort = await findFreePort();
    const webPort = await findFreePort();
    const apiBaseUrl = "http://127.0.0.1:" + apiPort;
    const webBaseUrl = "http://127.0.0.1:" + webPort;
    allowE2ECORSOrigin(webBaseUrl);

    const { createApp } = await import("./server");
    state.apiServer = http.createServer(createApp());
    await listenHTTP(state.apiServer, apiPort);

    state.viteServer = await createViteServer({
      root: process.cwd(),
      configFile: false,
      appType: "spa",
      plugins: [react()],
      server: {
        host: "127.0.0.1",
        port: webPort,
        strictPort: true,
        proxy: {
          "/api": {
            target: apiBaseUrl,
            changeOrigin: false
          }
        }
      }
    });
    await state.viteServer.listen();

    const browserPath = resolveBrowserExecutable();
    state.browser = await chromium.launch({ executablePath: browserPath, headless: true });
    const page = await state.browser.newPage();
    page.setDefaultTimeout(10_000);

    await authenticateIfNeeded(page, webBaseUrl);

    for (const check of checks) {
      await runBrowserCheck(page, check);
    }

    console.log("BlackLang generated browser e2e tests passed");
  } finally {
    await closeRuntime(state);
    if (ownsEphemeralSQLite) {
      await removeSQLiteDatabaseFiles(databaseUrl).catch(() => undefined);
    }
  }
}

function selectDatabaseUrl() {
  if (process.env.BLACKLANG_E2E_DATABASE_URL) {
    return process.env.BLACKLANG_E2E_DATABASE_URL;
  }
  if (databaseProvider === "sqlite") {
    return defaultE2EDatabaseUrl;
  }
  return process.env[databaseEnvName] ?? defaultGeneratedDatabaseUrl;
}

function allowE2ECORSOrigin(origin: string) {
  if (!corsOriginsEnvName) return;
  const existing = process.env[corsOriginsEnvName] ?? "";
  const origins = existing.split(",").map((item) => item.trim()).filter(Boolean);
  if (!origins.includes(origin)) {
    origins.push(origin);
  }
  process.env[corsOriginsEnvName] = origins.join(",");
}

async function authenticateIfNeeded(page: Page, baseUrl: string) {
  await page.goto(baseUrl, { waitUntil: "domcontentloaded" });
  if (!authEnabled) {
    const firstPage = checks[0]?.page ?? Object.keys(pageLabels)[0];
    if (firstPage) {
      await expectPageVisible(page, firstPage);
    }
    return;
  }

  await page.getByRole("button", { name: "Register", exact: true }).waitFor({ state: "visible" });
  await page.getByRole("button", { name: "Register", exact: true }).click();
  await page.locator('input[name="name"]').fill("BlackLang E2E");
  await page.locator('input[name="email"]').fill("blacklang-e2e@example.test");
  await page.locator('input[name="password"]').fill("blacklang-e2e-password");
  await page.getByRole("button", { name: "Create account", exact: true }).click();

  const firstPage = checks[0]?.page ?? Object.keys(pageLabels)[0];
  if (firstPage) {
    await expectPageVisible(page, firstPage);
  }
}

async function runBrowserCheck(page: Page, check: BrowserCheck) {
  await navigateToPage(page, check.page);

  for (const expectation of check.expectations) {
    if (expectation.kind === "text") {
      await expectVisibleText(page, expectation.value, "test " + check.name + " text expectation");
    }
    if (expectation.kind === "page") {
      await navigateToPage(page, expectation.value);
    }
    if (expectation.kind === "action") {
      await navigateToPage(page, check.page);
      await expectActionVisible(page, check, expectation.value);
    }
  }
}

async function navigateToPage(page: Page, pageName: string) {
  const label = pageLabels[pageName] ?? pageName;
  const navButton = page.getByRole("button", { name: label, exact: true }).first();
  if (await isVisible(navButton, 2_000)) {
    await navButton.click();
  }
  await expectPageVisible(page, pageName);
}

async function expectPageVisible(page: Page, pageName: string) {
  const label = pageLabels[pageName] ?? pageName;
  await expectVisibleText(page, label, "page " + pageName);
}

async function expectActionVisible(page: Page, check: BrowserCheck, actionName: string) {
  const label = actionLabelsByPage[check.page]?.[actionName] ?? actionName;
  const button = page.getByRole("button", { name: label, exact: true }).first();
  assert.ok(actionLabelsByPage[check.page]?.[actionName], "Browser e2e check " + check.name + " expected action " + actionName + " on page " + check.page + " but it is not declared in generated action metadata.");
  await button.waitFor({ state: "visible" });
}

async function expectVisibleText(page: Page, text: string, description: string) {
  const locator = page.getByText(text, { exact: false }).first();
  await locator.waitFor({ state: "visible" }).catch((error: unknown) => {
    throw new Error("Missing visible text for " + description + ": " + JSON.stringify(text) + ". " + String(error));
  });
}

async function isVisible(locator: Locator, timeout: number) {
  try {
    await locator.waitFor({ state: "visible", timeout });
    return true;
  } catch {
    return false;
  }
}

async function findFreePort() {
  return new Promise<number>((resolve, reject) => {
    const server = net.createServer();
    server.once("error", reject);
    server.listen(0, "127.0.0.1", () => {
      const address = server.address() as AddressInfo;
      server.close((error) => {
        if (error) reject(error);
        else resolve(address.port);
      });
    });
  });
}

async function listenHTTP(server: Server, port: number) {
  return new Promise<void>((resolve, reject) => {
    server.once("error", reject);
    server.listen(port, "127.0.0.1", () => resolve());
  });
}

async function closeHTTP(server: Server | undefined) {
  if (!server || !server.listening) return;
  await new Promise<void>((resolve, reject) => {
    server.close((error) => {
      if (error) reject(error);
      else resolve();
    });
  });
}

async function closeRuntime(state: RuntimeState) {
  await state.browser?.close().catch(() => undefined);
  await state.viteServer?.close().catch(() => undefined);
  await closeHTTP(state.apiServer).catch(() => undefined);
  if (authEnabled) {
    const authModule = await import("./routes/auth").catch(() => undefined) as AuthDatabaseModule | undefined;
    await authModule?.closeAuthDatabase?.();
  }
  const dbModule = await import("./db").catch(() => undefined) as PrismaDatabaseModule | undefined;
  await dbModule?.prisma?.$disconnect?.();
}

function resolveBrowserExecutable() {
  const candidates = [
    process.env.BLACKLANG_E2E_BROWSER_PATH,
    joinIfRoot(process.env.PROGRAMFILES, "Google", "Chrome", "Application", "chrome.exe"),
    joinIfRoot(process.env["PROGRAMFILES(X86)"], "Google", "Chrome", "Application", "chrome.exe"),
    joinIfRoot(process.env.LOCALAPPDATA, "Google", "Chrome", "Application", "chrome.exe"),
    joinIfRoot(process.env.PROGRAMFILES, "Microsoft", "Edge", "Application", "msedge.exe"),
    joinIfRoot(process.env["PROGRAMFILES(X86)"], "Microsoft", "Edge", "Application", "msedge.exe"),
    "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
    "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge",
    "/usr/bin/google-chrome",
    "/usr/bin/google-chrome-stable",
    "/usr/bin/chromium",
    "/usr/bin/chromium-browser"
  ].filter((candidate): candidate is string => Boolean(candidate));

  for (const candidate of candidates) {
    try {
      if (candidate && requireFile(candidate)) {
        return candidate;
      }
    } catch {
      continue;
    }
  }

  throw new Error("No browser executable found for generated browser e2e. Set BLACKLANG_E2E_BROWSER_PATH to a Chrome, Chromium, or Edge executable.");
}

function joinIfRoot(root: string | undefined, ...parts: string[]) {
  return root ? path.join(root, ...parts) : "";
}

function requireFile(filePath: string) {
  return statSync(filePath).isFile();
}

async function removeSQLiteDatabaseFiles(databaseUrl: string) {
  const filePath = sqliteFilePath(databaseUrl);
  if (!filePath) return;
  const absolute = path.resolve(process.cwd(), filePath);
  for (const suffix of ["", "-journal", "-wal", "-shm"]) {
    await fs.rm(absolute + suffix, { force: true });
  }
}

function sqliteFilePath(databaseUrl: string) {
  return databaseUrl.startsWith("file:") ? databaseUrl.slice("file:".length) : "";
}

await main();
`, tsBool(g.program.Auth != nil), tsBool(g.hasSeeds()), g.targetDatabase(), g.databaseEnvName(), g.defaultDatabaseURL(), g.defaultE2EDatabaseURL(), g.e2eCORSOriginsEnvName(), browserJSONStringMap(g.browserCheckPageLabels()), browserJSONNestedStringMap(g.browserCheckActionLabelsByPage()), browserJSONChecks(g.program.Tests))
}

func (g *webGenerator) defaultE2EDatabaseURL() string {
	if g.isPostgres() || g.isMySQL() {
		return g.defaultDatabaseURL()
	}
	return "file:./blacklang-e2e.db"
}

func (g *webGenerator) e2eCORSOriginsEnvName() string {
	if cors := g.corsConfig(); cors != nil && cors.Origins.Name != "" {
		return cors.Origins.Name
	}
	return ""
}

func (g *webGenerator) browserCheckPageLabels() map[string]string {
	labels := map[string]string{}
	for _, page := range g.navigationPages() {
		labels[page.Name] = g.uiLabelFallback("page."+page.Name, page.Name)
	}
	return labels
}

func (g *webGenerator) browserCheckActionLabelsByPage() map[string]map[string]string {
	actionsByPage := map[string]map[string]string{}
	for _, page := range g.program.Pages {
		entity, ok := g.findEntity(page.Source)
		if !ok {
			continue
		}
		actions := map[string]string{}
		for _, action := range page.Actions {
			actions[action] = g.browserCheckActionLabel(action, entity)
		}
		actionsByPage[page.Name] = actions
	}
	return actionsByPage
}

func (g *webGenerator) browserCheckActionLabel(action string, entity EntityDecl) string {
	switch action {
	case "create":
		return g.uiLabelFallback("action.new."+entity.Name, "New "+entity.Name)
	case "edit":
		return g.uiLabelFallback("action.edit", "Edit")
	case "delete":
		return g.uiLabelFallback("action.delete", "Delete")
	case "archive":
		return g.uiLabelFallback("action.archive", "Archive")
	case "restore":
		return g.uiLabelFallback("action.restore", "Restore")
	default:
		return g.uiLabelFallback("action."+action, identifierLabel(action))
	}
}

func tsBool(value bool) string {
	if value {
		return "true"
	}
	return "false"
}

func browserJSONStringMap(values map[string]string) string {
	content, err := json.MarshalIndent(values, "", "  ")
	if err != nil {
		return "{}"
	}
	return string(content)
}

func browserJSONNestedStringMap(values map[string]map[string]string) string {
	content, err := json.MarshalIndent(values, "", "  ")
	if err != nil {
		return "{}"
	}
	return string(content)
}

func (g *webGenerator) browserMatrixManifestJSON() string {
	manifest := struct {
		Version     string `json:"version"`
		App         string `json:"app"`
		Target      string `json:"target"`
		PlanCommand string `json:"planCommand"`
		RunCommand  string `json:"runCommand"`
		Policy      string `json:"policy"`
		Targets     []struct {
			Name   string `json:"name"`
			Family string `json:"family"`
			Env    string `json:"env,omitempty"`
		} `json:"targets"`
		GeneratedFiles []string `json:"generatedFiles"`
	}{
		Version:     "0.1",
		App:         g.program.App.Name,
		Target:      "web",
		PlanCommand: "npm run test:e2e:plan",
		RunCommand:  "npm run test:e2e:matrix",
		Policy:      "Plan mode is read-only; matrix run mode executes the generated e2e test once for each available browser target and skips missing optional targets unless no browser is available.",
		Targets: []struct {
			Name   string `json:"name"`
			Family string `json:"family"`
			Env    string `json:"env,omitempty"`
		}{
			{Name: "custom", Family: "chromium", Env: "BLACKLANG_E2E_BROWSER_PATH"},
			{Name: "chrome", Family: "chromium", Env: "BLACKLANG_E2E_CHROME_PATH"},
			{Name: "edge", Family: "chromium", Env: "BLACKLANG_E2E_EDGE_PATH"},
			{Name: "chromium", Family: "chromium", Env: "BLACKLANG_E2E_CHROMIUM_PATH"},
		},
		GeneratedFiles: []string{
			"src/blacklang.browser.test.tsx",
			"src/blacklang.e2e.test.ts",
			"src/blacklang.e2e.matrix.ts",
			"tests/browser-matrix.json",
		},
	}
	content, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return "{}\n"
	}
	return string(content) + "\n"
}

func (g *webGenerator) browserTestReadmeSection() string {
	if g.isAPIOnlyTarget() || !g.hasBrowserChecks() {
		return ""
	}
	return `## Browser E2E Matrix

Declared browser test blocks generate one-browser e2e and cross-browser matrix commands.

~~~bash
npm run test:e2e
npm run test:e2e:plan
npm run test:e2e:matrix
~~~

Run test:e2e:plan first for a read-only browser availability report. Matrix run executes the same generated e2e intent across available browser targets.

`
}

func (g *webGenerator) browserE2EMatrixTS() string {
	return fmt.Sprintf(`// Generated by BlackLang. Do not edit manually.

import { spawnSync } from "node:child_process";
import { statSync } from "node:fs";
import path from "node:path";

type BrowserFamily = "chromium";
type MatrixMode = "plan" | "run";

type TargetDefinition = {
  name: string;
  family: BrowserFamily;
  source: string;
  required: boolean;
  candidates: Array<string | undefined>;
};

type MatrixTarget = {
  name: string;
  family: BrowserFamily;
  source: string;
  required: boolean;
  available: boolean;
  executablePath?: string;
  reason?: string;
};

type MatrixRunResult = {
  name: string;
  family: BrowserFamily;
  source: string;
  passed: boolean;
  exitCode: number | null;
  signal: NodeJS.Signals | null;
  stdoutTail: string[];
  stderrTail: string[];
  error?: string;
};

const appName = %q;
const target = "web";
const databaseProvider = %q;
const checkCount = %d;
const policy = "Plan mode is read-only; matrix run mode executes the existing generated e2e test once for each available browser target and skips missing optional targets unless no browser is available.";

function main() {
  const mode = selectMode();
  const targets = resolveMatrixTargets();
  if (mode === "plan") {
    emit({
      success: true,
      command: "test:e2e:plan",
      mode,
      app: appName,
      target,
      databaseProvider,
      checkCount,
      ready: targets.some((item) => item.available),
      summary: summarizeTargets(targets, []),
      targets,
      policy,
      steps: [
        "Review available browser targets before running the matrix.",
        "Set BLACKLANG_E2E_BROWSER_PATH for a custom Chromium-based executable.",
        "Run npm run test:e2e:matrix to execute every available target."
      ]
    });
    return;
  }

  const runnable = targets.filter((item) => item.available && item.executablePath);
  if (runnable.length === 0) {
    emit({
      success: false,
      command: "test:e2e:matrix",
      mode,
      app: appName,
      target,
      databaseProvider,
      checkCount,
      ready: false,
      summary: summarizeTargets(targets, []),
      targets,
      results: [],
      policy,
      errors: ["No available browser executable found for generated e2e matrix."],
      steps: [
        "Install Chrome, Chromium, or Edge on the runner.",
        "Or set BLACKLANG_E2E_BROWSER_PATH to a Chromium-based executable."
      ]
    });
    process.exitCode = 1;
    return;
  }

  const results = runnable.map((item) => runTarget(item));
  const failed = results.filter((item) => !item.passed);
  emit({
    success: failed.length === 0,
    command: "test:e2e:matrix",
    mode,
    app: appName,
    target,
    databaseProvider,
    checkCount,
    ready: true,
    summary: summarizeTargets(targets, results),
    targets,
    results,
    skipped: targets.filter((item) => !item.available),
    policy,
    steps: [
      "Each matrix target runs the same generated e2e intent.",
      "Missing browser targets are skipped as optional unless no target is available.",
      "Use stdoutTail and stderrTail for compact failure triage."
    ]
  });
  if (failed.length > 0) {
    process.exitCode = 1;
  }
}

function selectMode(): MatrixMode {
  const args = new Set(process.argv.slice(2));
  if (args.has("--run") || args.has("run")) return "run";
  return "plan";
}

function summarizeTargets(targets: MatrixTarget[], results: MatrixRunResult[]) {
  return {
    total: targets.length,
    available: targets.filter((item) => item.available).length,
    skipped: targets.filter((item) => !item.available).length,
    runnable: targets.filter((item) => item.available && item.executablePath).length,
    passed: results.filter((item) => item.passed).length,
    failed: results.filter((item) => !item.passed).length
  };
}

function runTarget(target: MatrixTarget): MatrixRunResult {
  const executablePath = target.executablePath ?? "";
  const child = spawnSync(process.execPath, [tsxCLIPath(), path.join("src", "blacklang.e2e.test.ts")], {
    cwd: process.cwd(),
    env: {
      ...process.env,
      BLACKLANG_E2E_BROWSER_PATH: executablePath,
      BLACKLANG_E2E_BROWSER_NAME: target.name
    },
    encoding: "utf8",
    windowsHide: true
  });
  return {
    name: target.name,
    family: target.family,
    source: target.source,
    passed: child.status === 0,
    exitCode: child.status,
    signal: child.signal,
    stdoutTail: outputTail(child.stdout),
    stderrTail: outputTail(child.stderr),
    error: child.error?.message
  };
}

function resolveMatrixTargets(): MatrixTarget[] {
  const seenPaths = new Set<string>();
  return targetDefinitions().map((definition) => {
    let duplicateFound = false;
    for (const candidate of definition.candidates) {
      const executablePath = normalizeCandidate(candidate);
      if (!executablePath || !isExecutableFile(executablePath)) {
        continue;
      }
      const key = path.resolve(executablePath).toLowerCase();
      if (seenPaths.has(key)) {
        duplicateFound = true;
        continue;
      }
      seenPaths.add(key);
      return {
        name: definition.name,
        family: definition.family,
        source: definition.source,
        required: definition.required,
        available: true,
        executablePath
      };
    }
    return {
      name: definition.name,
      family: definition.family,
      source: definition.source,
      required: definition.required,
      available: false,
      reason: duplicateFound ? "Executable already covered by an earlier matrix target." : "No executable found in deterministic candidates."
    };
  });
}

function targetDefinitions(): TargetDefinition[] {
  return [
    {
      name: "custom",
      family: "chromium",
      source: "BLACKLANG_E2E_BROWSER_PATH",
      required: false,
      candidates: [process.env.BLACKLANG_E2E_BROWSER_PATH]
    },
    {
      name: "chrome",
      family: "chromium",
      source: "BLACKLANG_E2E_CHROME_PATH and known Chrome install paths",
      required: false,
      candidates: [
        process.env.BLACKLANG_E2E_CHROME_PATH,
        joinIfRoot(process.env.PROGRAMFILES, "Google", "Chrome", "Application", "chrome.exe"),
        joinIfRoot(process.env["PROGRAMFILES(X86)"], "Google", "Chrome", "Application", "chrome.exe"),
        joinIfRoot(process.env.LOCALAPPDATA, "Google", "Chrome", "Application", "chrome.exe"),
        "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
        "/usr/bin/google-chrome",
        "/usr/bin/google-chrome-stable"
      ]
    },
    {
      name: "edge",
      family: "chromium",
      source: "BLACKLANG_E2E_EDGE_PATH and known Edge install paths",
      required: false,
      candidates: [
        process.env.BLACKLANG_E2E_EDGE_PATH,
        joinIfRoot(process.env.PROGRAMFILES, "Microsoft", "Edge", "Application", "msedge.exe"),
        joinIfRoot(process.env["PROGRAMFILES(X86)"], "Microsoft", "Edge", "Application", "msedge.exe"),
        "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge",
        "/usr/bin/microsoft-edge",
        "/usr/bin/microsoft-edge-stable"
      ]
    },
    {
      name: "chromium",
      family: "chromium",
      source: "BLACKLANG_E2E_CHROMIUM_PATH and known Chromium install paths",
      required: false,
      candidates: [
        process.env.BLACKLANG_E2E_CHROMIUM_PATH,
        "/usr/bin/chromium",
        "/usr/bin/chromium-browser"
      ]
    }
  ];
}

function tsxCLIPath() {
  const cliPath = path.join(process.cwd(), "node_modules", "tsx", "dist", "cli.mjs");
  if (!isExecutableFile(cliPath)) {
    throw new Error("Generated e2e matrix could not find local tsx CLI at " + cliPath + ". Run npm install before test:e2e:matrix.");
  }
  return cliPath;
}

function normalizeCandidate(candidate: string | undefined) {
  return candidate?.trim() ?? "";
}

function joinIfRoot(root: string | undefined, ...parts: string[]) {
  return root ? path.join(root, ...parts) : "";
}

function isExecutableFile(filePath: string) {
  if (!filePath) return false;
  try {
    return statSync(filePath).isFile();
  } catch {
    return false;
  }
}

function outputTail(output: string | null | undefined) {
  const lines = String(output ?? "").split(/\r?\n/).map((line) => line.trim()).filter(Boolean);
  return lines.slice(-12);
}

function emit(value: unknown) {
  console.log(JSON.stringify(value, null, 2));
}

main();
`, g.program.App.Name, g.targetDatabase(), len(g.program.Tests))
}
